### ISSUE TITLE
OpenAI翻译时，有时会把好几段翻译结果合成一段表示

### ISSUE THREAD

**Issue by tuyoshi54** [bookfere/Ebook-Translator-Calibre-Plugin#103]
使用OpenAI 翻译 epub的时候，会随机出现多个段落英文翻译以后，不分段放在一个段落中。 而Google, Azure翻译同样的epub就没有这样的问题。

其他用户有类似现象吗？

**Comment by bookfere** [comment]
开启合并翻译功能了吗？如果开启了就是正常的，因为目前还没有太好的方法让 ChatGPT 始终保持合并段落后插入的标记。你可以尝试参考网友分享的经验 #95 调整提示词改善这种情况。
