### ISSUE TITLE
Ids get removed of elements(mobi format)

### ISSUE THREAD

**Issue by gammesB** [bookfere/Ebook-Translator-Calibre-Plugin#104]
This seems to specifically happen with the mobi format.
My contents hyperlinks don't work anymore after translating the file. 
Checking in calibre editor I can see that the p element of the header doesn't have a id anymore. 

Checking the contents the `<a href="infex_split_000.html#filepos100">chapter 1</a>` is still there.
But checking chapter 1 it went from `<p id="filepos100" class="calibre"><a href="infex_split_000.html#filepos100">chapter 1</a></p>`
To
`<p class="calibre">chapter 1</p>`

I first thought I could circumvent the problem by converting it to a epub in calibre and then clicking on "translate book" but then it will open a new clean list with sentences without all the sentence's I had translated/manual changed.

**Comment by bookfere** [comment]
Thank you for your feedback. The issue was resolved and will be applied in the next version.
