### ISSUE TITLE
翻译后的电子书文件不能正常打开，但是可以calibre上阅读。

### ISSUE THREAD

**Issue by just-createone** [bookfere/Ebook-Translator-Calibre-Plugin#106]
**能在calibre上正常阅读**
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/69511529/09512870-d848-4238-9277-caec655b6436)
**但是翻译后的电子书文件是这样的，不能正常打开。我需要获得翻译后的电子书文件。**
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/69511529/c9992484-2d44-4ed7-bd10-7e7260694fe2)

**Comment by anartigone** [comment]
需要更多信息，请尝试不同翻译引擎、不同电子书、保存路径，使用高级模式进行翻译并提供日志。

**Comment by just-createone** [comment]
发现有的电子书经过翻译后会有一个翻译后的可阅读的epub文件，但是有的电子书经过翻译后会出现上述问题，文件无法打开。以下是其中一本无法打开的电子书的翻译日志。（但可以在calibre上正常阅读）


![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/69511529/596638d8-44b3-45f4-9e03-23f2756125c9)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/69511529/6f937d93-4cf1-4051-8236-f69179702e03)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/69511529/b86fa662-0e81-4884-aee1-7908dc5487eb)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/69511529/426310df-c5d5-4f10-9bda-13c7ec0eff31)

**Comment by bookfere** [comment]
出现这个问题的电子书翻译用时大概有多长？和没有出现此问题的电子书相比，会更长一些吗？

**Comment by just-createone** [comment]
翻译时长取决于书本的内容长短，有的电子书比这本书长的多，但是最终导出的文件是正常的，这本书大概用了三到五分钟左右吧。
如果你的意思是在翻译过程中是不是耗时特别久，那答案是不是的，翻译速度还是比较快的，也能在calibre上正常阅读，就是我需要的导出的翻译后的epub文件异常（如上图）。

**Comment by bookfere** [comment]
重新翻译那本书，问题还会重现吗？如果能的话，请提供一下电子书文件，我这里测试一下。

**Comment by just-createone** [comment]
重新翻译后会出现相同的问题，如何提供给你，邮箱发送嘛？

**Comment by bookfere** [comment]
可以，邮箱是 bookfere@gmail.com。

**Comment by just-createone** [comment]
> 可以，邮箱是 [bookfere@gmail.com](mailto:bookfere@gmail.com)。

已发送

**Comment by bookfere** [comment]
试试这个版本：

[ebook-translator-202308172008.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12369149/ebook-translator-202308172008.zip)

**Comment by just-createone** [comment]
> 试试这个版本：
> 
> [ebook-translator-202308172008.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12369149/ebook-translator-202308172008.zip)

请问你发给我的这个插件版本怎么安装啊？是要把这个文件解压到calibre文件夹中的plugins文件夹中嘛？

**Comment by bookfere** [comment]
通过插件文件安装插件的步骤可以参考项目 Wiki 中的“[安装插件](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6)”。

**Comment by just-createone** [comment]
> 通过插件文件安装插件的步骤可以参考项目 Wiki 中的“[安装插件](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6)”。
问题已解决，但是安装完之后会有一个更新插件的提示，是不是刚修复的这个bug还没有上线？我需要更新嘛？是不是更新之后就会覆盖了你给我的这个版本的插件。
因为看到更新就有点想把他重启更新一下，有点强迫症。
