### ISSUE TITLE
Optimized feature suggestion: Implement command line interface support

### ISSUE THREAD

**Issue by laraws** [bookfere/Ebook-Translator-Calibre-Plugin#108]
When attempting to run this plugin in the terminal using the command 'calibre-debug --run-plugin "Ebook Translator"', the following output is displayed:
```bash
➜  ~ calibre-debug --run-plugin "Ebook Translator"       
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 47, in <module>
  File "site.py", line 43, in main
  File "calibre/debug.py", line 282, in main
  File "calibre/customize/__init__.py", line 312, in cli_main
NotImplementedError: The Ebook Translator plugin has no command line interface
```
It would be greatly appreciated if you could add support for a command line interface to this plugin. Thank you.

**Comment by bookfere** [comment]
This is a GUI plugin, and we currently do not have plan to implement non-GUI functionality, unless someone else contributes to it. Sorry for the inconvenience this may cause.

**Comment by ROBERT-MCDOWELL** [comment]
If you drive me which part of your code to modify so I can contribute to make it work in headless mode like ebook-convert
