### ISSUE TITLE
process stops at 99% always， and there is a message。进度停在99%，程序崩溃

### ISSUE THREAD

**Issue by WalleZJ** [bookfere/Ebook-Translator-Calibre-Plugin#110]
我在旧电脑 Win10使用Calibre 6.13，Translator版本 2.11版本，用来翻译epub书籍，一直没有太多问题。 但是最近买了一个新的电脑，把整个Calibre 库复制到新的电脑中，之后 就一直翻译出错。始终进度，停留在 99%。 而且窗口无法关闭，强制点击后 会崩溃Crash。重新启动后，点击输出，依然job停留在 99%的进度，然后查看log，有如下的报错。请帮忙解决下。（已经尝试过 软件和插件统一退回到旧的版本，依然报错。  新的6.25+2.12也一样的）
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/136595048/ad486580-6858-45a8-b0f9-2603c230d597)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/136595048/479c0e1f-1c9b-4dfa-ae6c-0cf5b1f29c1e)

**Comment by WalleZJ** [comment]
下面这张图 是点击关闭窗口按钮，崩溃前的截图。可以，看到 其实 所有段落，都已经翻译完了，但进度一直停留在 99%。
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/136595048/cccd87de-ad1e-4a42-abc5-ff89d637d4ca)

**Comment by bookfere** [comment]
你使用的网络是 IPv6 吗？我这里无法复现此错误，通过你提供的错误信息尝试修复了一下，试试看这个版本:

[ebook-translator-202308232234.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12420383/ebook-translator-202308232234.zip)

**Comment by WalleZJ** [comment]
另外 关于ipv6 ， 我用cmd ipconfig/all 能看到有ipv6 也有 ipv4的地址，所以不清楚到底是不是ipv6.    这个笔记本是 surface pro9，别的一般，wifi好像是比较新的那种，大概是ipv6。如果需要什么信息，可以帮助到你们收集错误原因，可以说的具体一点，我尽量配合。  再次，感谢你们的付出。

**Comment by bookfere** [comment]
这个问题与 asyncio 的事件循环（event loops）实现有关。Windows 自 Python 3.8 之后（新版 Calibre 用的是 3.10）默认使用的实现是 [ProactorEventLoop](https://docs.python.org/3.8/library/asyncio-eventloop.html#asyncio.ProactorEventLoop)（使用 Windows 的 [I/O Completion Ports](https://learn.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports) 机制），但是貌似在实际运行过程中存在缺陷，因此针对 Windows 插件暂时将事件循环策略更换为 [SelectorEventLoop](https://docs.python.org/3.8/library/asyncio-eventloop.html#asyncio.SelectorEventLoop) 来避免问题。

我不是太确定是这个错误是否因 IPv6 引起，只是在查资料的时候，看到类似的问题讨论中有人提了一嘴在 IPv4   没能重现错误。鉴于涉及到 asyncio 的底层实现，如果这个解决方法没太大问题，就暂时不花时间研究了。

谢谢你的反馈，也欢迎随时贡献代码。
