### ISSUE TITLE
[Feature Request] 支持排除匹配 CSS 选择器 的子元素 

### ISSUE THREAD

**Issue by sunnyh1220** [bookfere/Ebook-Translator-Calibre-Plugin#114]
当前的元素过滤规则只要element.text不为空，就不再往下遍历子元素，希望提供从element中删除与配置css选择器相匹配的的子element。（https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/blob/master/lib/element.py#L179）

我在翻译编程类书籍遇到以上问题，以下是示例：
这是数据库cache表一条数据的截图，我希望设置了过滤css选择器 （.fixedline）后，可以将代码部分过滤；
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/20295414/63866f39-5370-4f2b-b700-c7444029e975)

这是当前的翻译过后的截图：
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/20295414/81ce11d7-4d62-4763-ac57-aa1c91fd2322)

期望配置过滤规则后的样子：
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/20295414/989ac228-8fa3-4328-bea3-fed3e56c5355)

**Comment by bookfere** [comment]
目前针对某个段落，只保留了其中的 `<img>` 和 `<code>` 两种元素（即段落翻译完成后将其原样还原），后面的版本可以加个选项来支持通过 CSS 选择器自定义段落内要保留的元素。

**Comment by yyitsz** [comment]
可以先支持<pre>元素吗？
