### ISSUE TITLE
Can't choose gpt 4

### ISSUE THREAD

**Issue by nvmAlex** [bookfere/Ebook-Translator-Calibre-Plugin#116]
When i try to choose gpt 4 as a model, it automatically switches back to gpt 3.5 turbo, what can i do?

**Comment by bookfere** [comment]
Please try to update this fixed version and check if it resolves the issue.

[ebook-translator-202308311852.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12485349/ebook-translator-202308311852.zip)

**Comment by nvmAlex** [comment]
It still switches back to gpt 3.5 turbo once i save

**Comment by bookfere** [comment]
I suggest that you uninstall the current version first and then restart Calibre. After that, you can install the fixed version above using the "load plugin from file" button in Calibre preferences.
