### ISSUE TITLE
能否设置多个gpt的key。

### ISSUE THREAD

**Issue by tongcuyu** [bookfere/Ebook-Translator-Calibre-Plugin#117]
gpt每个账号，大概短时间能用几次是可以的，用多了就不行了，需要等一两天才能继续使用。
 我像能不能多申请几个账号，然后再key里，进行设置，每个账号轮换使用。
刚一个账号一段时间没有响应就换另一个账号的key。

或者以两到三账号为一个组，每个账号分别轮换翻译，
当第一组没反应了，再换下一组。
这样就账号就不会因为短时间内大量翻译二出现这种问题。

\~~~~~~~~~~~~~~~~~~~~

It's ok for gpt to use each account, probably a few times for a short period of time, but not if you use it more than that, and you need to wait a day or two before you can continue to use it.
I'm wondering if it's possible to apply for a few more accounts, and then in the key, set it up so that each account is rotated.
If one account doesn't respond for a while, change the key to another account.

Or maybe a group of two or three accounts, each rotating through the translations.
When the first group does not respond, then change the next group.
This way, the accounts will not have this problem because of a large number of translations in a short period of time.

**Comment by bookfere** [comment]
当前引擎是支持多密钥的。你可以在引擎设置中填写，一行一个。目前的策略是，当遇到响应中含有字符  `401`、`unauthorized` 和 `quota` 是，插件就会换用下一个密钥。

Multiple keys for engines have already been supported. You can add one key per line in the engine settings. The current strategy is that the plugin will automatically switch to the next key if it receives a response containing `401`, `unauthorized`, or `quota`.

**Comment by tongcuyu** [comment]
然而并不行，我已经试过了，这个问题一直存在着，
gtp存在问题，会很长长时间都不动，但是并没有提示失败或者其他的，其他的账号也没有用，
我现在每次都手动换其他key，停止..开始..换key，如此循环着。非常苦闷。
起码有个时间上的时间也好

**Comment by bookfere** [comment]
你设置的重试次数是多少？由于每次重试等待时间都会增加，这可能是很长时间没反应的原因。

**Comment by tongcuyu** [comment]
一段时间他就不怎么动了，有时他会提示错误（而彻底停止），有时不是，就是不动，
有时遇到这种情况，切换代理服务器会解决。

进度里面的提示是：

错误信息：无法从翻译引擎API获取数据。
无法解析返回的响应。原始数据：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests


参数
并发限制 3
 时间间隔 10.0
重试次数 5
 超时 1
超过错误次数停止翻译 7

**Comment by bookfere** [comment]
长时间不动和你设置的重试次数有关，5 次重试大概会花费 10 分钟的时间。出现 Too Many Requests 错误就是因为请求太频繁了，由于免费版 ChatGPT 一分钟只允许 3 次请求，建议将并发设为 1 间隔设为 20 秒，以避免此错误。

**Comment by bookfere** [comment]
谢谢建议。如果今后有较多这种需求再考虑添加。
