### ISSUE TITLE
[Feature request] Allow to save paritally translated book

### ISSUE THREAD

**Issue by econo202** [bookfere/Ebook-Translator-Calibre-Plugin#119]
It would be a great feature if it was possible to save progress when translating a book and you reach quota of the translation engine.
Now you have to keep the plugin open until you can continue.

**Comment by wangshuihua** [comment]
Actually, the plugin does support caching the translated content if the Cache Setting remains enabled as the default option. 

After reopening, it will NOT start all over again to re-translate the previously translated content, but will skip and proceed to translate the remaining content. 

You can feel free to close and open the plugin during translation without worrying about losing your progress.

**Comment by econo202** [comment]
Great! I didn't notice cache option that was turned off. Now works as I expected.
