### ISSUE TITLE
建议给chat gpt添加屏蔽审查的脚本或者内置绕开审查的代码供用户选择！

### ISSUE THREAD

**Issue by MZHMXH** [bookfere/Ebook-Translator-Calibre-Plugin#12]
建议给chat gpt添加屏蔽审查的脚本或者内置绕开审查的代码供用户选择！ @bookfere

**Comment by bookfere** [comment]
你所说的“审查”具体指的是什么？ChatGPT 不会审查所翻译的内容吧。

**Comment by MZHMXH** [comment]
> 


这是有关于chat gpt“绕过审核禁用数据监管”的参考贴子地址
https://www.cnblogs.com/JanYork/p/16981220.html

https://www.south-plus.net/read.php?tid-1777775.html

这是关于chat gpt “绕过审核禁用数据监管”的相关项目以及它的油猴脚本安装地址
https://github.com/bigemon/ChatGPT-ToolBox

https://greasyfork.org/zh-CN/scripts/456901-chatgpt%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA

**Comment by bookfere** [comment]
插件所调用的 ChatGPT API 不能像官方提供的聊天式 ChatGPT 那样保持上下文，因此针对聊天式 ChatGPT 的 Hack 无法用在 API 上。即便手动维护上下文，对于翻译一本书来说代价也太大。

从你提供的这些资料看，ChatGPT 的“审查”不会对于“翻译”这一功能产生什么负面影响，因此项目没有添加此需求的意愿。

不过，之后插件会添加自定义翻译引擎功能，会把请求和响应数据交给用户处理，如果你想尝试自己的需求，可以利用此功能。

**Comment by MZHMXH** [comment]
> 插件所调用的 ChatGPT API 不能像官方提供的聊天式 ChatGPT 那样保持上下文，因此针对聊天式 ChatGPT 的 Hack 无法用在 API 上。即便手动维护上下文，对于翻译一本书来说代价也太大。
> 
> 从你提供的这些资料看，ChatGPT 的“审查”不会对于“翻译”这一功能产生什么负面影响，因此项目没有添加此需求的意愿。
> 
> 不过，之后插件会添加自定义翻译引擎功能，会把请求和响应数据交给用户处理，如果你想尝试自己的需求，可以利用此功能。

chat gpt可能会屏蔽翻译一些违规的内容吧，如果是这样的话会对原文内容翻译的完整性有着很大的影响，这个问题可以有办法解决吗？

**Comment by bookfere** [comment]
使用 ChatGPT 需要遵守他们的“[使用政策](https://openai.com/policies/usage-policies)”，如果原文内容不违反这些规则就没问题，否则就需要换用其他翻译引擎。

**Comment by MZHMXH** [comment]
> 使用 ChatGPT 需要遵守他们的“[使用政策](https://openai.com/policies/usage-policies)”，如果原文内容不违反这些规则就没问题，否则就需要换用其他翻译引擎。

关键是可能文章内含有违规内容我要是不知道的话造成内容屏蔽也会伤脑筋，有没有办法检测并且指出那段内容含有违规内容呢，或者违规内容保留原文跳过翻译

**Comment by bookfere** [comment]
ChatGPT 的 API 没有提供特定响应信息用来判断是否违反使用政策，因此插件也无法检测所翻译内容是否违反了它的使用政策。

如果你确实遇到了这个问题，建议保留原文供参考，或者参考 ChatGPT 提供的[文档](https://platform.openai.com/docs/api-reference/chat/create)自行测试一下，看是它的回复是否有规律可循，然后用插件中的“不要翻译”功能排除含有这些词汇的内容。
