### ISSUE TITLE
代理配置项没有用户名和密码，翻译报错无法授权代理成功

### ISSUE THREAD

**Issue by xiaoxpai** [bookfere/Ebook-Translator-Calibre-Plugin#120]
希望可以增加用户名&密码选项
![图片](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/39144603/7c593d1b-47a2-4d57-a67f-6094117474d9)

**Comment by bookfere** [comment]
你可以将用户信息附加到 IP 或域名上，比如 `username:password@127.0.0.1`（用户名和密码之间用 `:` 隔开，然后用 `@` 连接 IP 或域名）。感觉这不是一个太常用的功能，就暂时不添加到界面上了，只是在输入框中添加了一个提示。

**Comment by anartigone** [comment]
需要复杂代理配置的话，可以用第三方工具辅助，具体参考[这篇讨论](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/discussions/83)。如果严重依赖代理服务器上网的话，建议直接在路由器上配置好网络层隧道，以避免在应用层中不必要的折腾。
