### ISSUE TITLE
使用自定义词汇表的时候出现bug.

### ISSUE THREAD

**Issue by 9zang** [bookfere/Ebook-Translator-Calibre-Plugin#121]
比如我定义cult这个单词不翻译,但是实际上翻译的时候,会把包含cult的单词culture翻译为cult,或者 "cult加乱码符号ure".
这个设定很奇怪,能否设置为必须完全匹配才按照我们预设的词汇表翻译?
希望作者修复这个bug.

**Comment by 9zang** [comment]
我本意是想通过词汇表纠正一些不常用的词汇的翻译结果,但是这样的bug会导致一些常用词汇出现问题

**Comment by 9zang** [comment]
还比如km这个缩写,机翻会翻译为千米,但实际上情况是一些其他编码的缩写,我希望他干脆不翻译.我把这个词写入词汇表,但是workmanship这种包含km这两个字母的词会被强行翻译为km

**Comment by bookfere** [comment]
谢谢反馈。这个问题在 https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/91#issuecomment-1641307607 提到过。目前词汇表只是简单替换词汇表中的单词，没有精确的分词功能。

对于用空格分隔单词的语言，如英语，可以通过为词汇表中的词汇添加空格来控制替换。比如，要保持 km 不翻译，可以在 `km` 之后加一个空格，因为通常 `km` 前面紧接着数字，如 `32km`，这样就可以防止 `workmanship` 中的 `km` 不被替换。

再比如，要想`wing`总是翻译成`翼`，可在词汇表中的 `wing` 前后都加一个空格，以确保 `following` 中的 `wing`  不被翻译。

**Comment by 9zang** [comment]
> 谢谢反馈。这个问题在 [#91 (comment)](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/91#issuecomment-1641307607) 提到过。目前词汇表只是简单替换词汇表中的单词，没有精确的分词功能。
> 
> 对于用空格分隔单词的语言，如英语，可以通过为词汇表中的词汇添加空格来控制替换。比如，要保持 km 不翻译，可以在 `km` 之后加一个空格，因为通常 `km` 前面紧接着数字，如 `32km`，这样就可以防止 `workmanship` 中的 `km` 不被替换。
> 
> 再比如，要想`wing`总是翻译成`翼`，可在词汇表中的 `wing` 前后都加一个空格，以确保 `following` 中的 `wing` 不被翻译。

好的,我懂了,谢谢解答,我去试试看

**Comment by 9zang** [comment]
> 谢谢反馈。这个问题在 [#91 (comment)](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/91#issuecomment-1641307607) 提到过。目前词汇表只是简单替换词汇表中的单词，没有精确的分词功能。
> 
> 对于用空格分隔单词的语言，如英语，可以通过为词汇表中的词汇添加空格来控制替换。比如，要保持 km 不翻译，可以在 `km` 之后加一个空格，因为通常 `km` 前面紧接着数字，如 `32km`，这样就可以防止 `workmanship` 中的 `km` 不被替换。
> 
> 再比如，要想`wing`总是翻译成`翼`，可在词汇表中的 `wing` 前后都加一个空格，以确保 `following` 中的 `wing` 不被翻译。

当我把一个单词比如wing前后都加上空格时,是否意味着当这个单词刚好是一句的末尾最后一个单词,其后面附加了逗号句号冒号书名号之类的符号时,将不会按照我们定义的词汇表被识别?

**Comment by bookfere** [comment]
目前是的，插件对替换没有做任何干预。

**Comment by 9zang** [comment]
> 目前是的，插件对替换没有做任何干预。

好的,谢谢解答
