### ISSUE TITLE
[请求支持] 请求添加对GPT-API中转站的支持

### ISSUE THREAD

**Issue by Benson1997** [bookfere/Ebook-Translator-Calibre-Plugin#123]
请求添加对GPT-API中转站的支持，能否再GPT的接口上，添加一个自定义的请求网址(默认使用https://api.openai.com)，这样如果自己有需要，可以改成其他请求的地址（同样都是GPT模型）。

比如：可以将请求的openai地址`https://api.openai.com`改为地址`https://api.xxxxx.com

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/a9d7fca9-9643-4d45-b48f-cbcd1a5e5be8)

  "engine_preferences": {
    "ChatGPT": {
      "url": "https://api.openai.com",
      "api_keys": [
        "sk-***********************************************"
      ],
      "model": "gpt-3.5-turbo",
      "target_lang": "Chinese (Simplified)"
    },

另外，代理也已开启了 。

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/e6b3e14f-b42e-423b-a280-06eb7f6ffda7)

**Comment by Benson1997** [comment]
https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/34

按这个issue中的代码，设置后，提示的是  403错误。

**Comment by bookfere** [comment]
选择 ChatGPT (OpenAI) 后，是可以设置自定义端点的：

<img width="549" alt="chatgpt-screenshot" src="https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/29969316/d52931ec-712d-4239-888c-cbe8e68d5f66">

**Comment by Benson1997** [comment]
端点这里设置了，还是不行呢，提示403错误

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/78ea8810-dcfb-4be8-a614-4a609cf5b885)

同样的环境下，google free是可以的。
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/322280be-9466-4d21-8e32-87bcfe8451bd)

**Comment by bookfere** [comment]
一般情况下第三方服务提供的 API 请求端点应该是和 OpenAI 一致的，类似 `https://api.xxxxxx.com/v1/chat/completions` 而不只是一个域名。建议查阅你所用服务商的文档，确认一下具体的请求端点。

**Comment by Benson1997** [comment]
好的，谢谢老大！非常感谢
