### ISSUE TITLE
[ERROR] I cannot translate books!

### ISSUE THREAD

**Issue by gbr000** [bookfere/Ebook-Translator-Calibre-Plugin#124]
Procedures:

1. Open Calibre (last version 6.20) < select book
2. Click translate book (v.2.1.4) icon in main toolbar
3. After succesfully translated all without errors (both AZW3 and PDF, I tested)
4. final step would be clicking "OUTPUT" and an error is throw everytime

ERROR:

```
calibre, version 6.26.0
ERROR: Unhandled exception: <b>TypeError</b>:expected str, bytes or os.PathLike object, not NoneType

calibre 6.26  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Count Pages (1, 13, 1) && Ebook Translator (2, 1, 4)
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.advanced", line 591, in output_ebook
  File "calibre_plugins.ebook_translator.lib.conversion", line 124, in translate_ebook
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by bookfere** [comment]
It's likely the plugin could not obtain the output path properly. What is the path that you set for output?

**Comment by gbr000** [comment]
OK! Now I have figured out! I choose the path but when I changed to the next tab, path configuration is not saved!! 

So it may need a fix for that! Thanks in advance,

**Comment by bookfere** [comment]
Yes, it was a bug. I just fixed it. Thank you for mentioning it.
