### ISSUE TITLE
GPT中转的问题

### ISSUE THREAD

**Issue by kingfer30** [bookfere/Ebook-Translator-Calibre-Plugin#127]
你好, 我需要配置GPT中转的地址，经过看了这个issue #34 明确配置和评论区的一致，仍然测试不通过：
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/34082198/bd9e4637-d2d9-4763-906e-a5c75594b0e8)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/34082198/81cbb5b7-1301-47c0-801b-bfb145586076)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/34082198/f54c8c22-38e7-4c75-b204-f958c3769712)

API地址： https://api.aiguoguo199.com/v1/chat/completions
这个中转的作者关闭了国内IP请求，国内必须魔法才能使用，但是我在其他软件和页面均可以使用：
next-web：
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/34082198/ddac1834-6c40-42cc-8847-f182783f9013)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/34082198/b41a3d71-fc5e-433c-b9e4-f0a2d031df4a)

apifox: 
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/34082198/757c991b-e65e-4593-a406-5958f437d6a7)

请问还有什么遗漏的配置吗 ?

**Comment by bookfere** [comment]
你使用的服务会禁止某些用户代理请求，如插件使用的 Python-urllib。你可以在 `Headers` 中随便添加一个 `User-Agent` 来解决这个问题，如：`"User-Agent": "Any-Agent-You-Want"`。

**Comment by kingfer30** [comment]
感谢! 有效, 可以标记一下, 方便其他人使用
