### ISSUE TITLE
标题的译文能否也当做段落来处理，或者新增一个可选项，选择标题译文换行。

### ISSUE THREAD

**Issue by Benson1997** [bookfere/Ebook-Translator-Calibre-Plugin#128]
具体译文细节如下：

下面这个是我们 Ebook-Translator  翻译的

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/71c8c088-36e8-4c58-87bb-b354c16ca7c3)

隔壁沉**插件的译文，如下

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/1b5d1de3-21be-4b00-a625-efe82e8201f5)

根据段落（标题）换行，章节目录更直观。因为经常会遇到一些小标题文字比较多，译文合并在一起，就会出现一大片的加粗内容。

比如下面这段文字：

（原文）
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/716167ac-390e-4729-a73b-c49af2578472)

（ Ebook-Translator  译文）
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/85747838-5e4a-4316-a8f9-9dcf5b79e2cd)

（ 沉***  译文）
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/b0dd7911-ec20-4e7c-af90-59b4e30f51ef)

补充细节：他们把目录也翻译了，不知道我们的开发计划中有没有呢，批量功能很强大，期待 Ebook-Translator 越来越强大 👍👍

**Comment by Benson1997** [comment]
[标题译文分段_demo.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/12642658/_demo.zip)

**Comment by bookfere** [comment]
谢谢反馈。标题换行的问题已在提交 75f8885a14a33b596462ebb679df131e3de67203 中得到解决。导航目录的翻译需求同 #105，此功能已在提交 3a2d943af103b451e318e02dec468152292d4057 中添加。这些修改会在下个版本可用。你也可以按照[安装步骤](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6)下载安装代码库中的最新版本（非发布版本未测试可能会存在错误）。

另外，我看到你截图中 ChatGPT 回答了带有问句的标题，这个问题可以在设置中修改提示词来避免。

**Comment by Benson1997** [comment]
好的，谢谢大佬🤞

**Comment by Benson1997** [comment]
> 谢谢反馈。标题换行的问题已在提交 [75f8885](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/commit/75f8885a14a33b596462ebb679df131e3de67203) 中得到解决。导航目录的翻译需求同 #105，此功能已在提交 [3a2d943](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/commit/3a2d943af103b451e318e02dec468152292d4057) 中添加。这些修改会在下个版本可用。你也可以按照[安装步骤](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6)下载安装代码库中的最新版本（非发布版本未测试可能会存在错误）。
> 
> 另外，我看到你截图中 ChatGPT 回答了带有问句的标题，这个问题可以在设置中修改提示词来避免。

请问您说的修改提示词（是下图这个译文吧），是应该怎么修改呢

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/64dbb6a7-dc79-415c-ae4d-ff558818485f)

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/127983c4-f71e-4ed8-bdc6-df6cb4981961)

**Comment by bookfere** [comment]
如果不想用英文，你也可以用中文撰写提示词内容，只需确保保留 `<slang>` 和 `<tlang>` 这两个标记即可。比如：

> 你是一位细心的译者，负责将任何给定的内容从 `<slang>` 翻译成 `<tlang>`，注意不要回答任何疑问句式和解释任何术语。

你可以根据具体情况调整提示词。填写好保存，可以先通过测试功能用之前出错的内容来验证是否符合预期，也可以用高级模式打开那本书，重新翻译之前翻译有误的段落。

**Comment by Benson1997** [comment]
嗯呢，明白了，谢谢。就是gpt在翻译的时候，把标题当作一个问题，直接给回答了去，哈哈🤣

**Comment by Benson1997** [comment]
老大，用命令行下载不下来最新的包，是不是要装git程序到本机上才行（小白一枚）。
如果可以的话，能不能麻烦发一下最新的包到我的邮箱一份呢，非常感谢 ben987@foxmail.com ，等着你更新呢。
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/07ef647c-d42a-4240-b3d2-2f269f831730)

**Comment by Benson1997** [comment]
直接把zip下载下来，文件拖到Ebook Translator.zip里面覆盖之前的文件，这样可以实现插件更新吗？

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/026eba6e-d460-4e0f-af80-978f49ff4775)

**Comment by bookfere** [comment]
这种方式应该是没问题的。现在插件添加了一个落地页面：[https://translator.bookfere.com](https://translator.bookfere.com)，每次提交代码都会生成一个最新版本，今后你可通过页面上的【__Rolling Version__】按钮下载使用。

**Comment by Benson1997** [comment]
好的，谢谢哦！🤞
