### ISSUE TITLE
可否添加对LibreTranslate和Lingva的支持

### ISSUE THREAD

**Issue by killgfat** [bookfere/Ebook-Translator-Calibre-Plugin#13]
可否添加对于自建服务[LibreTranslate](https://github.com/LibreTranslate/LibreTranslate)和[Lingva](https://github.com/TheDavidDelta/lingva-translate)的支持

**Comment by bookfere** [comment]
和 #6  一样，之后的版本会增加自定义翻译引擎功能来满足这个需求。
