### ISSUE TITLE
使用chatgpt翻译txt文档结果只翻译很少部分文字

### ISSUE THREAD

**Issue by wuzimi** [bookfere/Ebook-Translator-Calibre-Plugin#14]
下午测试了一个txt文本，大概5000字符，一整大段。
可能是高峰时段缘故，进度一直很慢，可以从日志看出下面提示：
无法从翻译引擎API获取数据。
5 秒后重试。
正在重试 ...（300秒后超时）
无法从翻译引擎API获取数据。
10 秒后重试。
正在重试 ...（300秒后超时）
无法从翻译引擎API获取数据。
30 秒后重试。
正在重试 ...（300秒后超时）

最后终于输出，但是最后仅仅翻译了一小段，然后就提示翻译完成：译文：我不觉得我准备好去那里了，因为现在大型语言模型与物理世界没有联系。它们只是通过预测一个词将跟随另一个词的方式工作，但它们没有运动控制，它们不会行动在世界上，它们不会感知世界。也许一旦我们掌握了这个，人工智能研究就应该停止一段时间，这是一种谨慎的态度。在我看来，弗洛伊德是一位有历史地位的心理学家，也是心理学家的培训必备内容之一，因为他显然是对心理学产生了巨大影响的人之一。然而，他的某些具体观点，比如肛门阶段、口腔阶段、原始场景、阴茎妒忌情结等等，都无法经受住检验的考验。

**Comment by lion-no-back** [comment]
调用ChatGPT服务来翻译PDF文档，速度慢的吓人，这个可以优化下嘛，就单个句子翻译速度可以向openai-translator发展嘛，不过该说不说，扩展很好用的，谢谢你的开发分享

**Comment by bookfere** [comment]
@wuzimi 如果要翻译的内容过长，建议分段翻译。之后插件也会尝试将过长的段落拆分开再交给翻译引擎翻译。

@lion-no-back 貌似最近 ChatGPT 限速了，之前没这么慢。除了购买他们的服务和提高自己的网速外，ChatGPT 的响应速度应该是没太大优化空间的。有的项目使用了 [SSE](https://en.wikipedia.org/wiki/Server-sent_events) 技术来实现响应文本的实时显示，可以从心理上缓解长时间等待的焦虑感，但是每次请求总耗时差别应该不会太大。

**Comment by LvShuaiChao** [comment]
我也遇到了这个问题
![Snipaste_2023-05-02_20-06-08](https://user-images.githubusercontent.com/35528109/235661503-aa8fdb12-4092-46aa-9b23-f9c86129f875.png)

**Comment by bookfere** [comment]
@LvShuaiChao 从截图看不出无法获取数据的具体原因。你可以把尝试次数设为 0，看看它会出现什么错误提示。

**Comment by Jackie00765** [comment]
有些文字很短，但是也翻譯不到，去到中途便停止了。

**Comment by ConstasJ** [comment]
ChatGPT API有3RPM和40000TPM的速率限制。（即每分钟3次请求，40000个token）
希望作者能加入适应OpenAI速率限制的功能。

**Comment by wuzimi** [comment]
您好，目前在使用最新版本的额翻译插件。使用chatgpt时，虽然我设置了并发，但是为什么我注意到我把一篇文章分割成14个chunk后，可以注意到仍是顺序翻译的，并没有实际按并发进行？所以想问问这是怎么回事。

lion-no-back ***@***.***> 于2023年4月13日周四 21:07写道：

**Comment by bookfere** [comment]
@wuzimi 功能的实现有点问题，下一个版本会做优化。
