### ISSUE TITLE
设置”合并翻译“为15000字符，使用自定义gpt-3.5-turbo-16k-0613来翻译，会提示HTTP Error 504: Gateway Time-out。请问如何设置超时时间？

### ISSUE THREAD

**Issue by GoTop** [bookfere/Ebook-Translator-Calibre-Plugin#146]
我使用python中，使用相同的第三方chatgpt api、prompt、需要翻译的段落，进行翻译，估计3-4分钟就可以正常返回翻译内容了。

第三方的chatgpt后台显示使用的token和费用如下：
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/1784319/3f1b33d9-53dc-4b3a-99b3-fb24309bd605)

在Calibre中中，如果设置插件”合并翻译“为10000字符，也可以正常获取到翻译结果。

但是当设置”合并翻译“提高到15000字符时，大概3-5分钟，会出现HTTP Error 504: Gateway Time-out：
```
错误信息：无法从翻译引擎API获取数据。
无法解析返回的响应。原始数据：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 504: Gateway Time-out
```

就算将插件的"HTTP请求"-”超时（秒）“设置为6000s，也就是100分钟，还是会出现相同的错误
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/1784319/67770078-919b-4f9e-82d7-9f936f63dc7e)

第三方的chatgpt后台未显示此次请求产生的账单，说明翻译请求未发送到服务器。

不知道插件使用request()时，是否有字符限制？

不知道插件除了"HTTP请求"-”超时（秒）“，是不是还有默认的超时时间设置？
或者是Calbre里已经设置了请求网络连接的时间？

**Comment by bookfere** [comment]
[504 Gateway Timeout](https://www.rfc-editor.org/rfc/rfc9110#name-504-gateway-timeout) 指的是第三方服务器无法及时从上游服务器获取到响应，和客户端的超时设置没关系。

**Comment by GoTop** [comment]
> [504 Gateway Timeout](https://www.rfc-editor.org/rfc/rfc9110#name-504-gateway-timeout) 指的是第三方服务器无法及时从上游服务器获取到响应，和客户端的超时设置没关系。

但是我使用python代码来获取翻译，是正常的
使用插件获取10000字符分段的原文的翻译，插件也能正常返回翻译结果
