### ISSUE TITLE
是否能在选择翻译段落的页面，提供导出、导入原文和译文的选项（cvs文件）？这样就能方便修改译文了

### ISSUE THREAD

**Issue by GoTop** [bookfere/Ebook-Translator-Calibre-Plugin#147]
支持导入、导出原文和译文之后，会编程的话就可以实现很多小修改了

**Comment by bookfere** [comment]
你可以通过插件菜单中的缓存管理器打开缓存所在位置，所有数据都存在 SQLite 文件中。

**Comment by GoTop** [comment]
> 你可以通过插件菜单中的缓存管理器打开缓存所在位置，所有数据都存在 SQLite 文档中。

感谢，有SQLite数据就好操作了。

比如我这里提到的问题：https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/146#issue-1923938065
我可以使用python代码直接获取每段原文的译文，然后写入SQLite文件中
