### ISSUE TITLE
Br标签和p标签

### ISSUE THREAD

**Issue by weloe** [bookfere/Ebook-Translator-Calibre-Plugin#149]
br标签的不识别为一行，全部并起来当成一段翻译了，p标签的段落正常视为一行，要怎么解决？

**Comment by bookfere** [comment]
此问题同 #148，目前解决了翻译后换行被删除的问题，你可以通过插件主页 http://translator.bookfere.com 通过”Rolling Version”按钮下载安装修复后的版本。
