### ISSUE TITLE
GPT合并翻译时候出现“错误信息：无法解析返回的响应。原始数据：The read operation timed out”

### ISSUE THREAD

**Issue by tongcuyu** [bookfere/Ebook-Translator-Calibre-Plugin#150]
怎么办，什么bug吗？
而且这句话在原文中就不出现了，现在还要手动一句一句的查看一遍，否则漏一句都不知道。
希望下个版本修复这个bug

**Comment by bookfere** [comment]
对于需要较长时间运算的输入 ChatGPT 的响应有时会很慢，你可以在设置中把请求超时时间设置长一些再试试看。

另外，错误中的“原始数据”指的不是“原文数据”而是响应的原始数据，想要查看哪句没翻译，可以使用高级模式，里面可以看到每个段落的翻译状态。
