### ISSUE TITLE
ChatGPT issues

### ISSUE THREAD

**Issue by jessykalycia** [bookfere/Ebook-Translator-Calibre-Plugin#152]
Decided to leave feedback after attempting a translation from a japanese book into english. So far, I found these issues while using the translation app:

1. I was unable to change ChatGPTs (OpenAI) prompt a few times (I had already changed it before). I tried to just delete to go back to the original, and then I made some more changes to the prompt, but it took a while to change the prompt.

**Comment by bookfere** [comment]
Duplicate to #153.
