### ISSUE TITLE
[fueature request] new option, color change

### ISSUE THREAD

**Issue by luto01** [bookfere/Ebook-Translator-Calibre-Plugin#157]
I think adding an option to change the color of the orginal text in addition to changing the color of the translation would be a cool option. On a kindle reader that is black and white the only option to set off is a shade of gray. The natrual choice would be gray orginal text and black clear translation text.

**Comment by bookfere** [comment]
Resolved in 6fe26fb024a42800c5a4383c6ef30fe6d1d3b3a4.
