### ISSUE TITLE
Google翻译引擎设置问题

### ISSUE THREAD

**Issue by EdisonWendy** [bookfere/Ebook-Translator-Calibre-Plugin#158]
Google (Advanced)翻译引擎设置中的“PROJECT_NUMBER_OR_ID|KEY PATH”中的“key_path”要怎么写才正确呢，JSON密钥文件都下载到电脑本地了，但是路径咋填都不行，测试显示如下：
“Traceback (most recent call last):
File “calibre_plugins.ebook_translator.components.engine”, line 66, in translate_text
File “calibre_plugins.ebook_translator.engines.google”, line 129, in translate
File “calibre_plugins.ebook_translator.engines.google”, line 59, in _get_credential
File “subprocess.py”, line 966, in __init__
File “subprocess.py”, line 1435, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。”
麻烦指导一下。

**Comment by bookfere** [comment]
应该是用 | 分隔的项目 ID 和密钥文件的绝对路径。

假设你的项目 ID 是 `my-project`，密钥文件名是 `my-key.json`，是存放桌面上的（以 Windows 为例）。那么应该这样写：

```
my-project|C:\Users\YOURNAME\Desktop\my-key.json
```

目前这个功能比较简单，未来应该会改得更易用些。

**Comment by EdisonWendy** [comment]
> 应该是用 | 分隔的项目 ID 和密钥文件的绝对路径。
> 
> 假设你的项目 ID 是 `my-project`，密钥文件名是 `my-key.json`，是存放桌面上的（以 Windows 为例）。那么应该这样写：
> 
> ```
> my-project|C:\Users\YOURNAME\Desktop\my-key.json
> ```
> 
> 目前这个功能比较简单，未来应该会改得更易用些。

我是按照“my-project|C:\Users\YOURNAME\Desktop\my-key.json”这个格式填写的，难道是我的json文件不正确吗？测试仍然显示下面这段提示：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.google", line 129, in translate
  File "calibre_plugins.ebook_translator.engines.google", line 59, in _get_credential
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1435, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by bookfere** [comment]
原来的可用性有问题，现在改了一下，你可以再试试看。

注意，插件将身份验证方式改成了 [Application Default Credentials（ADC）](https://cloud.google.com/docs/authentication/provide-credentials-adc)，不再需要项目 ID 和 JSON 文件，只需要在你的本机环境中运行以下命令，然后登录 Google 账户准许必要的权限即可。插件会读取当前活跃配置的项目 ID。

```
gcloud auth application-default login
```

新修改后的功能可能还存在问题，遇到问题随时反馈。
