### ISSUE TITLE
deepl free api custom url

### ISSUE THREAD

**Issue by toprak** [bookfere/Ebook-Translator-Calibre-Plugin#160]
i have a server deployed deeplx i want to use it instead of calibre deploy itself, thanks.

**Comment by anartigone** [comment]
You can refer to the deeplx part of [this guide](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/discussions/83#Linux).

```
{
    "name": "DeepL X",
    "languages": {
        "source": {
            "English": "EN"
        },
        "target": {
            "中文": "ZH"
        }
    },
    "request": {
        "url": "http://127.0.0.1:1188/translate",
        "method": "POST",
        "headers": {
            "Content-Type": "application/json"
        },
        "data": {
            "source_lang": "<source>",
            "target_lang": "ZH",
            "text": "<text>"
        }
    },
    "response": "response['data']"
}
```

**Comment by toprak** [comment]
@anartigone where can i find it on win?

**Comment by toprak** [comment]
@anartigone by the way i really liked your blog's css, can you post it?

**Comment by anartigone** [comment]
> @anartigone this is really good written text, since its in chinese i tried to translate it into turkish but it was not that clear however, i will try to find a way to use your guide to run it on windows, i guess you already gave a tool that works on all platform but i still dunno how to use tor as proxy etc. i will try my best, thanks for guide.

Sorry for the delayed reply. 
Due to the considerations for dealing with the specific network complexity in Mainland China, the guide was wrote in Chinese. But I can explain to you whenever you get stuck or having question going through the guide.

**Comment by toprak** [comment]
@anartigone ah, i figured it out thanks

**Comment by anartigone** [comment]
> @anartigone by the way i really liked your blog's css, can you post it?

I'm happy to hear that. Just published my css. You can get it from [here](https://github.com/anartigone/Black-Rose).

**Comment by toprak** [comment]
@anartigone thanks for posting, i will send the method in discussion on this, maybe they will help some win users

**Comment by anartigone** [comment]
> @anartigone thanks for posting, i will send the method in discussion on this, maybe they will help some win users

That would be great. Please share it and I'll be lurking around in your discussion to help people who needs troubleshooting.

**Comment by toprak** [comment]
@anartigone posted it on your discussion [post ](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/discussions/83) with really broken english, hope it'd understandable thanks for that guide again.
