### ISSUE TITLE
最近使用gpt翻译内容，会莫名其妙把把内容变成英文。

### ISSUE THREAD

**Issue by tongcuyu** [bookfere/Ebook-Translator-Calibre-Plugin#161]
我使用了合并翻译，把英语或者日文翻译成中文，都会出现，返回内容变成英语的情况。
应该是bug，求修复

**Comment by tongcuyu** [comment]
以前没有这个bug，现在越来越严重，有点GPT没法用了.

**Comment by bookfere** [comment]
修改过提示词吗？默认提示词 `Translate the given content from <slang> to <tlang> only` 不应该出现这个问题。
