### ISSUE TITLE
可否加入srt字幕文件的翻译功能

### ISSUE THREAD

**Issue by tongcuyu** [bookfere/Ebook-Translator-Calibre-Plugin#162]
srt文件只是一个按照特定格式编写的txt文本，只需要跳过时间轴等等，就可以生成双语字幕。
实用度极高

**Comment by anartigone** [comment]
我尝试过用这个做srt字幕，效果很满意，但只是[一个临时解决方案](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/discussions/107)。如果将来能有内置功能用就会方便很多了，因为不同的翻译引擎所输出的结果需要用不同的Regex技巧去替换。

**Comment by personalsrc-git** [comment]
可以借用Anthemion Jutoh 这个epub编辑器作为中介，将srt文本导入Anthemion Jutoh ，生成epub文件，再用Ebook-Translator-Calibre-Plugin翻译，翻译后导出txt，再复制到srt里就行。

**Comment by bookfere** [comment]
现在已为插件添加了翻译 SRT 字幕的功能，欢迎试用反馈。

**Comment by anartigone** [comment]
> 现在已为插件添加了翻译 SRT 字幕的功能，欢迎试用反馈。

非常好用，太棒了
