### ISSUE TITLE
DeepL X problem

### ISSUE THREAD

**Issue by dyoghenes** [bookfere/Ebook-Translator-Calibre-Plugin#17]
Hi!

Playing around DeepL X I could get it working as a small python code. Using this code returns to me HTTP Error 400: Bad Request in Calibre, and a 404 error in the DeepLX:

```
{
    "name": "DeepLX",
    "languages": {
        "source": {
            "Source Language": "DE"
        },
        "target": {
            "Target Language": "EN-GB"
        }
    },
    "request": {
        "url": "http://127.0.0.1:1188/translate",
        "method": "POST",
        "data": {
            "text": "<text>",
            "source": "DE",
            "target": "EN-GB"
        }
    },
    "response": "response"
}
```

**Comment by dyoghenes** [comment]
I see. However, when I use the following python code, the translation works:

> import httpx, json
> 
> deeplx_api = "http://127.0.0.1:1188/translate"
> 
> data = {
> 	"text": "Hello World",
> 	"source_lang": "EN",
> 	"target_lang": "ZH"
> }
> 
> post_data = json.dumps(data)
> r = httpx.post(url = deeplx_api, data = post_data).text
> print(r)

Is this unrelated?

**Comment by bookfere** [comment]
The request data in your code is in JSON format, so you need to set the `Content-Type: application/json` in the request headers to specify the format of the data being sent:

```
"headers": {
    "Content-Type": "application/json"
}
```

**Comment by dyoghenes** [comment]
I tried that and it still returned the same error message (400 in Calibre,
404 in DeepLX).

**Comment by bookfere** [comment]
Please try the latest version 1.2.2. I tested the code snippet below and it works.

```
{
    "name": "DeepL X",
    "languages": {
        "source": {
            "German": "DE"
        },
        "target": {
            "English (British)": "EN-GB"
        }
    },
    "request": {
        "url": "http://127.0.0.1:1188/translate",
        "method": "POST",
        "headers": {
            "Content-Type": "application/json"
        },
        "data": {
            "source_lang": "<source>",
            "target_lang": "<target>",
            "text": "<text>"
        }
    },
    "response": "response['data']"
}
```

**Comment by dyoghenes** [comment]
It works perfectly now, thank you!
