### ISSUE TITLE
[功能建议] 实验性地仅采用换行符作为非gpt类翻译引擎合并翻译请求时的段落标记

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#174]
**可以是一个可选项**，经验上，我认为相较于使用特殊标记，这会对大多数传统机器翻译引擎要友好，也能节省一些字符数。具体到实现细节上，可以请求翻译前移除开头的空格、tab以及一些无意义的Unicode字符（日语小说经常有），返回翻译后再根据原文还原。

**Comment by WeeAris** [comment]
关于之前讨论中提到的[使用```\n\n```作标记在译后编辑时不易检查](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/discussions/69#discussioncomment-7149973)的问题，可以考虑在编辑页面仍保留特殊标记，仅在发起翻译请求的前后进行标记和```\n\n```的转换，这样呈现给用户的仍是带序号的标记。
另外，我对特殊标记令检查错误更容易这一点持怀疑态度，我用Deepl翻译了一本30万字的韩语小说，对译文进行关键字查找到约180个残留的“变形”的标记，其中部分标记附近的译文还重复或遗漏了。即便我已经知道了这些标记的序号，但在编辑界面看起来还是很乱，逐个修改起来很吃力。

**Comment by bookfere** [comment]
当前最新的代码分割段落默认使用了 `\n\n`，但是不太确定之前插入标记的方式是否有必要加一个选项让其成为可选。

**Comment by GoTop** [comment]
> 当前最新的代码分割段落默认使用了 `\n\n`，但是不太确定之前插入标记的方式是否有必要加一个选项让其成为可选。

请问最新版是指2.2.0版吗？

我在这个版本里看到的还是用{{id_数字}}来分隔呢

**Comment by WeeAris** [comment]
> > 当前最新的代码分割段落默认使用了 `\n\n`，但是不太确定之前插入标记的方式是否有必要加一个选项让其成为可选。
> 
> 请问最新版是指2.2.0版吗？
> 
> 我在这个版本里看到的还是用{{id_数字}}来分隔呢

不是2.2.0，是指最新源码

**Comment by WeeAris** [comment]
> 当前最新的代码分割段落默认使用了 `\n\n`，但是不太确定之前插入标记的方式是否有必要加一个选项让其成为可选。

我测试了一下，好像确实没有必要

**Comment by bookfere** [comment]
那就不加了。打算加完译文校验功能（#82）就发个新版本。

**Comment by GoTop** [comment]
> 那就不加了。打算加完译文校验功能（#82）就发个新版本。

等了两个星期了，新版有着落了么？

**Comment by WeeAris** [comment]
> > 那就不加了。打算加完译文校验功能（#82）就发个新版本。
> 
> 等了两个星期了，新版有着落了么？

等得及的话可以用滚动版

**Comment by GoTop** [comment]
> 滚动版

滚动版只的是最新commit的版本么？

**Comment by WeeAris** [comment]
> > 滚动版
> 
> 滚动版指的是最新commit的版本么？

是的

**Comment by bookfere** [comment]
> > 那就不加了。打算加完译文校验功能（#82）就发个新版本。
> 
> 等了两个星期了，新版有着落了么？

抱歉年底这段日子没有太多空余时间。如 @WeeAris 建议，你可以随时访问插件主页通过【Rolling Release】安装最新版。
