### ISSUE TITLE
CHATGPT Issues

### ISSUE THREAD

**Issue by bclx1** [bookfere/Ebook-Translator-Calibre-Plugin#177]
I'm using ChatGPT to translate an e-book, but after about 150 paragraphs it starts giving me problems, throwing up various errors and forcing me to translate line by line. Eventually, I had the same problem with Google Translate, which started working again after a few hours. GPT continues to have the same difficulty. The attempt I made with DeepL didn't even do any kind of translation. Before, I was able to translate normally.

It starts skipping steps and then gives an error: 
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests
==============================
Original: ‘Then why would one need to push a mortar up a mountain to be meaningful when you don't bring the pestle along?’
-----------------------------------
Error: Failed to retrieve data from translate engine API.
Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 185, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

**Comment by bookfere** [comment]
This is a duplicate issue similar to #156. Please adjust the "**Concurrency limit**" and "**Interval**" in settings to avoid this error.
