### ISSUE TITLE
技术类文档中存在代码如何避免翻译

### ISSUE THREAD

**Issue by kingnight** [bookfere/Ebook-Translator-Calibre-Plugin#18]
如题，技术类文档中，很多存在代码片段，如何避免被翻译；正则无法匹配

**Comment by bookfere** [comment]
感觉这不太容易用程序自动处理，因为不同电子书的代码片段格式差异很大。插件今后打算添加一个翻译监控面板，到时可以在上面提供一些功能，可以通过一些特征（比如有些代码片段所在的元素共用同一个 class 属性）来排除不需要翻译的段落。
