### ISSUE TITLE
the plugin crashes my internet and I need to reboot my router.

### ISSUE THREAD

**Issue by Raygoga** [bookfere/Ebook-Translator-Calibre-Plugin#181]
When I use the ebook translator plugin, with the free Google engine, it translates one book but if I want to translate another one or if I want to do it simultaneously, I lose the internet connection and it forces me to restart the router to be able to do another translation.
On other occasions, I have to restart the router a couple of times to be able to translate a single book, I don't know if the programme makes too many connections and collapses the internet or what the problem is... With the free DeepL, the same thing happens to me, it gets up to 80% of translation and then it crashes.

**Comment by bookfere** [comment]
I don't think the internet issue is connected to the plugin. If you're considering whether the problem might be due to the frequency of requests, I'd recommend testing it out by adjusting the request concurrency and interval settings.

**Comment by Raygoga** [comment]
Thank you very much for the answer, what parameters do you suggest I apply? How do I modify them?
