### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by modkhi** [bookfere/Ebook-Translator-Calibre-Plugin#185]
Hi, I have not been able to get this plugin to work, and it keeps giving me this output:

```calibre, version 2.64.0 (win32, embedded-python: True)
Translation job failed: Failed: [Chinese > English] Translating "The villains in the whole family are crazy about criticism, but only the junior sister is funny"

[Chinese > English] Translating "The villains in the whole family are crazy about criticism, but only the junior sister is funny"
Python function terminated unexpectedly
  near "ON": syntax error (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
  File "site-packages\calibre\utils\ipc\worker.py", line 130, in arbitrary_n
  File "calibre_plugins.ebook_translator.lib.conversion", line 72, in convert_item
  File "calibre_plugins.ebook_translator.lib.cache", line 151, in set_info
sqlite3.OperationalError: near "ON": syntax error
```
I got this by using the Batch Mode. When using the Advanced Mode, it just crashes calibre entirely and does not give me the option to copy the error message at all.

I have tried other novels, other languages (both to and from) and also testing the translation engine in the settings will also crash calibre.

I do have a few other plugins installed on calibre, mainly for converting books and for integrating with my Kobo ereader. Is it possible they could be conflicting?

**Comment by bookfere** [comment]
Before anything else, I'd recommend installing the latest version from https://translator.bookfere.com by grabbing the "Rolling Version" to see if the issue still lingers. Additionally, could you let me know the Calibre version you're using?
