### ISSUE TITLE
支持GPT的二次翻译来大幅提高翻译质量

### ISSUE THREAD

**Issue by Arthur-WWW** [bookfere/Ebook-Translator-Calibre-Plugin#188]
推上网友提供的思路，通过prompt让GPT翻译两次来大幅改善翻译质量。
第一次直译，第二次在第一次直译的基础上进行意译。
https://twitter.com/dotey/status/1707478347553395105?t=fc_M1vSQHYYX6YB9paznRg&s=19

**Comment by WeeAris** [comment]
> 推上网友提供的思路，通过prompt让GPT翻译两次来大幅改善翻译质量。 第一次直译，第二次在第一次直译的基础上进行意译。 https://twitter.com/dotey/status/1707478347553395105?t=fc_M1vSQHYYX6YB9paznRg&s=19

分多次请求的话直接集成到插件里就太复杂了，一次请求完成又很难保持格式稳定

**Comment by GoTop** [comment]
我有一个思路：
让插件按设定字数进行分段，然后自己编程，获取缓存里的sqlite文件里的英文分段，然后直接调用chatgpt api翻译（这里可以自己设计prompt，使用两段式翻译），然后将翻译结果写入sqlite文件，最后调用插件生成书籍

**Comment by Benson1997** [comment]
过渡修饰译文，有时候可能会适得其反吧

**Comment by Arthur-WWW** [comment]
分享这个思路网友做过一系列测试（我贴的link），翻译质量有大幅提高，从prompt看就是对直译的内容进行改写来降低机翻感，我可以找一段英文来测试是否自定义prompt直接返回意译就可以完成，还是一定需要打印出直译的内容。我的理解是打印出直译内容就是为了对比意译有没有偏离原意，用于翻译文章时的人工校对，但对于直接翻译整本书，尤其是机翻整本书，译文流畅更重要，有些翻译错误是可以接受的，这样的机翻主要是用于快速阅读一些英文书籍，不是用于精读。

**Comment by WeeAris** [comment]
> 分享这个思路网友做过一系列测试（我贴的link），翻译质量有大幅提高，从prompt看就是对直译的内容进行改写来降低机翻感，我可以找一段英文来测试是否自定义prompt直接返回意译就可以完成，还是一定需要打印出直译的内容。我的理解是打印出直译内容就是为了对比意译有没有偏离原意，用于翻译文章时的人工校对，但对于直接翻译整本书，尤其是机翻整本书，译文流畅更重要，有些翻译错误是可以接受的，这样的机翻主要是用于快速阅读一些英文书籍，不是用于精读。

在Flores-101等评测数据集中表现怎么样？

**Comment by bookfere** [comment]
@Arthur-WWW 了解了。先标记一下，今后应该会实现。

**Comment by Arthur-WWW** [comment]
经过测试，确实可以通过修改prompt后直接返回第二次的意译来成书

**Comment by GoTop** [comment]
> 经过测试，确实可以通过修改prompt后直接返回第二次的意译来成书

能把prompt发来看看么

**Comment by Arthur-WWW** [comment]
在prompt里加上“仅返回第二次意译的最终结果，不要返回任何中间过程”就可以了

**Comment by GoTop** [comment]
> 仅返回第二次意译的最终结果，不要返回任何中间过程

多谢，我去试了一下。如果不让gpt输出中间直译的话，它就不会先直译，再根据直译的结果进行意译。

这和gpt的原理有关，好像叫做chain of thought

**Comment by Arthur-WWW** [comment]
如果是这样的话，那还是需要通过开发来处理返回结果才能达到最佳效果

GoTop ***@***.***> 于 2024年3月4日周一 09:31写道：

**Comment by riverai** [comment]
> 之前有位网友“[卡娃娃](https://bookfere.com/post/1057.html/comment-page-3#comment-32036)”提过一个类似的 TA 称之为“回译”的功能，TA 没有给出这个词的具体定义，好像是”英译中，中译英，英译中“这样来回翻译，但是不知道这有没有科学依据。
> 
> 我在翻译文章的时候会使用 ChatGPT 校验，发现很多时候它的翻译看起来很流畅，但是并不精准，也可能是我更偏好尽可能忠实还原原文的表达，不太喜欢过度意译。如果让 ChatGPT 根据它翻译出来的内容再次翻译，会不会与原文偏离得更远？

我看过一些测试，那种“意译”出来的版本，质量相对直译的差很多，除开流畅一无是处。
