### ISSUE TITLE
use of glossaries

### ISSUE THREAD

**Issue by killo3967** [bookfere/Ebook-Translator-Calibre-Plugin#19]
I think it could be very interesting to implement glossaries for translations.
For example in Spanish the word "cabo" has two possible meanings "end of a rope" and "military rank". If what I am translating is a nautical work, I should be able to choose the first one and not the second one. A clear example is the novels of Honor Harrington, which have naval themes and very specific terminology. A glossary would allow all the novels to be translated with the same terminology. 
I propose that the "glossary file" contain word pairs that are substituted and can also include the specific options to exclude certain content (and future posibilities), as if it were a configuration file for how to do the translation.
This does not mean that you have to worry about the graphics part of creating the file as it would be a text file. Only to could select the file.
There are many book series that would benefit from this possibility and users could exchange these files.

**Comment by bookfere** [comment]
Thanks for your suggestion and further thoughts. We will put this on our work list.

**Comment by killo3967** [comment]
Oh no, thanks to you for let me read a lot of books not published in my language. Your plugin is a dream come true.

**Comment by bookfere** [comment]
Thank you for your kind words. It was my pleasure to help you read more books.
