### ISSUE TITLE
Trim lengthy letters in translations generated by Google (free)

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [bookfere/Ebook-Translator-Calibre-Plugin#190]
I'm wondering if there's a way to delete excessive letter or limit them to like 4 letters max after translating using google translate (free) because when translating from some languages (like japanese or korean) to english sometimes the letter will be translated into long one like aaaaaaaa, eeeeee and so on

**Comment by bookfere** [comment]
Could you share some examples for testing? I'm not familiar with these two languages.

**Comment by YukinoshitaYukino123** [comment]
here some examples:
Korean
![excessive1](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/128869659/1a83e7ac-91d3-4578-972a-19082dd5084f)
![excessive2](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/128869659/b9073ff4-c90d-4b32-9549-b2ebcf96fdac)
Japanese
![excessive3](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/128869659/99ac2a2d-c533-4abe-9681-5287a2f3bf33)

**Comment by bookfere** [comment]
Based on your original post, is it okay to cut off long letters when they repeat more than four times?

**Comment by YukinoshitaYukino123** [comment]
Yes, because it's usually just sound of expression like aaahh, ooooh and etc.
