### ISSUE TITLE
希望能够支持gemini-pro！

### ISSUE THREAD

**Issue by sagehere** [bookfere/Ebook-Translator-Calibre-Plugin#193]
感谢作者开发了如此有用的插件！让我们读者能够跨越语言的鸿沟！
最近谷歌推出了gemini-pro，据说效果堪比GPT-4。由于gemini-pro的API调用需要依赖专门的库，因此自定义引擎时难以设置。
希望作者能够跟进gemini-pro，万分感谢！

**Comment by bookfere** [comment]
谢谢建议。遗憾的是由于 Gemini 的地区限制，我这里没法测试。

不过它提供了 [**REST API**](https://ai.google.dev/tutorials/rest_quickstart)，也就是说你应该是可以通过自定义引擎使用它的。你可以尝试先在[**这里**](https://makersuite.google.com/app/apikey)获取 API 密钥，然后使用下面的示例，将里面的 **YOURKEYHERE** 换成你的密钥。

如果你测试没问题，我就可以根据这个示例将其添加到内置翻译引擎中。

```
{
    "name": "Gemini",
    "languages": {
        "source": {
            "English": "English"
        },
        "target": {
            "Chinese": "Chinese"
        }
    },
    "request": {
        "url": "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=YOURKEYHERE",
        "method": "POST",
        "headers": {
            "Content-Type": "application/json"
        },
        "data": {
            "contents": [{
                "role": "user",
                "parts": [{"text":  "Translate <source> to <target>: <text>."}]
            }]
        }
    },
    "response": "response['candidates'][0]['content']['parts'][0]['text']"
}
```

**Comment by sagehere** [comment]
测试了一下，没有很大的问题。但有以下注意点：
1、由于目前是免费使用的，所以要注意注意调用频率，目前免费的版本好像是每分钟60次；
2、由于gemini-pro存在safety_settings这个参数，如果翻译文本的内容存在敏感词汇（此处不得不吐槽目前太严格了！！），建议加上
safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_ONLY_HIGH"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_ONLY_HIGH"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_ONLY_HIGH"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_ONLY_HIGH"
  }
]
参数。
PS：即使加上了依旧很严格，测试翻译了《冰与火之歌》某段名场面，结果就是BLOCKED……

**Comment by Arthur-WWW** [comment]
太恶心了吧，这也要敏感词😱

**Comment by tongcuyu** [comment]
是的 google这玩意可变态的。
我最早用Claude 一句一句翻译时候，
开始还没问题，后来全不行。
怎么“催眠”都不行

**Comment by tongcuyu** [comment]
快点添加吧，Google的东西就是争分夺秒，
趁现在赶紧白嫖

**Comment by HZzz2** [comment]
+1 想白嫖下谷歌

**Comment by tongcuyu** [comment]
这个频率怎么设置啊，软件那里设置不起作用

**Comment by sagehere** [comment]
@bookfere 
最近又深度测试了一下，发现在 20231218135354 这个版本中由于谷歌模型自身的问题有些“或许”涉及性话题的内容会返回以下信息：
{
  "promptFeedback": {
    "blockReason": "OTHER"
  }
}
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 189, in get_result
  File "calibre_plugins.ebook_translator.engines.custom", line 130, in parse
  File "<string>", line 1, in <module>
KeyError: 'candidates'
当遇到这种情况时，插件貌似会忽略引擎设置中对于重试次数的设置，不断重试，最后卡死。
希望作者能够注意到这个BUG！
谢谢！

**Comment by Benson1997** [comment]
> 谢谢建议。遗憾的是由于 Gemini 的地区限制，我这里没法测试。
> 
> 不过它提供了 [**REST API**](https://ai.google.dev/tutorials/rest_quickstart)，也就是说你应该是可以通过自定义引擎使用它的。你可以尝试先在[**这里**](https://makersuite.google.com/app/apikey)获取 API 密钥，然后使用下面的示例，将里面的 **YOURKEYHERE** 换成你的密钥。
> 
> 如果你测试没问题，我就可以根据这个示例将其添加到内置翻译引擎中。
> 
> ```
> {
>     "name": "Gemini",
>     "languages": {
>         "source": {
>             "English": "English"
>         },
>         "target": {
>             "Chinese": "Chinese"
>         }
>     },
>     "request": {
>         "url": "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=YOURKEYHERE",
>         "method": "POST",
>         "headers": {
>             "Content-Type": "application/json"
>         },
>         "data": {
>             "contents": [{
>                 "role": "user",
>                 "parts": [{"text":  "Translate <source> to <target>: <text>."}]
>             }]
>         }
>     },
>     "response": "response['candidates'][0]['content']['parts'][0]['text']"
> }
> ```

老大，language 这段，可以添加多种语言吗，或者像默认的那种可以出下拉框选择。（之前的自定义翻译引擎中也有这个需求😊）

` "languages": {
>         "source": {
>             "English": "English"
>         },
>         "target": {
>             "Chinese": "Chinese"`

**Comment by bookfere** [comment]
@Benson1997 直接往上加即可：

```
"languages": {
    "source": {
        "English": "English",
        "German": "Germain",
        "Japanese": "Japanese"
    },
    "target": {
        "Chinese-SC": "Simplified Chinese",
        "Chinese-TC": "Traditional Chinese"
   }
}
```

**Comment by Benson1997** [comment]
> @Benson1997 直接往上加即可：
> 
> ```
> "languages": {
>     "source": {
>         "English": "English",
>         "German": "German",
>         "Japanese": "Japanese"
>     },
>     "target": {
>         "Chinese-SC": "Simplified Chinese",
>         "Chinese-TC": "Traditional Chinese"
>    }
> }
> ```

好的，感谢🤞

**Comment by bookfere** [comment]
Resolved by the commit 17e3a09fc879bd1420a87f06636d1c09aa479658.
