### ISSUE TITLE
能否将序号数字这些排除翻译？

### ISSUE THREAD

**Issue by DamienLee2017** [bookfere/Ebook-Translator-Calibre-Plugin#2]
由于在国内，网络信号不是很好，看日志很多~“原文：5.1.1”这样的数字都要走一遍接口进行翻译，有时候网络不好还要重试好几遍，然后返回的结果还是“5.1.1”，这样就造成了大量的时间浪费，我翻译了一篇150多页的，有6004个翻译项目，估算了下，需要近一天的时间？？

**Comment by bookfere** [comment]
谢谢建议。今后会添加偏好设置，可用来过滤待翻译内容。
