### ISSUE TITLE
【Bug】使用 ChatGPT 翻译书籍，还当上老师了！

### ISSUE THREAD

**Issue by kairyo** [bookfere/Ebook-Translator-Calibre-Plugin#20]
<img width="667" alt="截屏2023-04-21 13 44 19" src="https://user-images.githubusercontent.com/23257723/233550087-97a70e24-57f9-4463-b0e7-06addfa06b23.png">
应该是文章里有一段问话，GPT 直接就回复上了，是否有可能在调用时，可以有一些限制，减少这样的错误发生。
下图是另一个错误，应该是类似的。
<img width="543" alt="截屏2023-04-21 13 47 22" src="https://user-images.githubusercontent.com/23257723/233550508-4583d6c3-9409-4c1a-94a2-bbf5a25cbdb3.png">

**Comment by bookfere** [comment]
谢谢反馈。插件提供了自定义 ChatGPT 提示词功能（在设置中选择 ChatGPT 后会显示在下方），你可以利用此功能调节 ChatGPT 的回复。比如，对于擅自回复翻译内容的问题，可以将提示词 `Translate the content into {tlang}: {text}` 改成 `Translate the content into {tlang} and do not reply: {text}`，修改完成后可以通过测试功能观察翻译结果。

![ebook-translator-calibre-plugin](https://user-images.githubusercontent.com/29969316/233608878-7e293b48-14ed-4aa6-a8b3-b16196f218f9.png)

![translation-engine-tester](https://user-images.githubusercontent.com/29969316/233605971-c3d52cad-da62-4752-994a-14422ae417de.png)

**Comment by kairyo** [comment]
不好意思，没有仔细看可以用户自定义的功能。非常感谢提供的软件和插件！

**Comment by bookfere** [comment]
不客气。之后在使用插件的过程中遇到任何问题欢迎随时反馈。

**Comment by kairyo** [comment]
目前有个新问题，就是 ChatGPT提示词，我已经修改并进行了保存，但是我第二天重新打开又需要重新再修改一次（修改结果保存不了）

**Comment by bookfere** [comment]
测试了一下没能重现这个问题。你在修改后点击【保存】按钮了吗？如果确认点击了，可以测试一下，修改后保存，然后关掉并重新打开 Calibre，看修改结果还存不存在。

**Comment by kairyo** [comment]
<img width="730" alt="截屏2023-04-24 18 49 46" src="https://user-images.githubusercontent.com/23257723/233975406-a3d02273-9a71-473c-b80c-9d04d094b631.png">
<img width="649" alt="截屏2023-04-24 18 48 04" src="https://user-images.githubusercontent.com/23257723/233975420-a1791061-b0c2-4354-889d-ce7b30af02a3.png">

**Comment by bookfere** [comment]
我想起来了，这个错误应该是设置好提示词后，点击【测试】按钮后就会出现。如果是这个问题的话，这个问题已经在这个提交 f1d672ec6ca0ae52cdd852e7f0fe2fda41f17b84 中修复了。如果问题还会重现，可以运行以下命令获取一个最新版本试试看：

```
git clone https://github.com/bookfere/Ebook-Translator-Calibre-Plugin.git
cd Ebook-Translator-Calibre-Plugin
git archive --format zip --output ../Ebook-Translator-Calibre-Plugin.zip master
```

**Comment by kairyo** [comment]
已经尝试，新插件会报错，不能存储用户修改后的 提示语。
另外：将提示语设为 do not reply 比 do not answer 更好一些。

**Comment by kairyo** [comment]
修改 提示词 报错！

**Comment by bookfere** [comment]
谢谢反馈，此问题会在下次提交中修复。
