### ISSUE TITLE
ChatGPT 报错 Error: expected string or bytes-like object, got 'generator'

### ISSUE THREAD

**Issue by Alyssalalala** [bookfere/Ebook-Translator-Calibre-Plugin#200]
之前都能正常使用，突然报错，显示

Error: expected string or bytes-like object, got 'generator'

求解答！谢谢

**Comment by sagehere** [comment]
> 之前都能正常使用，突然报错，显示
> 
> Error: expected string or bytes-like object, got 'generator'
> 
> 求解答！谢谢

你应该是使用的稳定版，然后使用了术语表。
稳定版2.2.0使用CHATGPT同时开启术语表时就会遇到这样的情况，你关掉术语表就好用了。同时自定义引擎貌似没有这样的问题。
