### ISSUE TITLE
与原文行数不一致的译文位置应与译文位置设置一致

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#208]
原来`{{id_n}}`如果合并失败，那么文本还是可以显示出来的，只不过是好几个原文，后面跟着一大段翻译，这样其实还能看。
现在的换行版本如果翻译失败，是直接丢失原文，导致不可用。
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/3f6c9eeb-be78-4f7f-bb9f-68680cdccfc1)

**Comment by GoTop** [comment]
Rolling Release版本里有些短的段落，gpt会合并起来翻译，然后后面的原文和译文就会错乱了

目前的正式版，使用<id-数字>来标记段落，就算有几段错乱了，后面的段落还是能对应回来

**Comment by bookfere** [comment]
是原文丢失吗？按照目前的处理方式，原文和译文都不应该丢失的，否则就是需要修复的错误。如果是感觉译文丢失，建议检查一下译文是否合并到了前面的段落中。下面是目前的处理方式：

假设待翻译段落的合并单元如下：

```
test paragraph 1

test paragraph 2

test paragraph 3

test paragraph 4

test paragraph 5
```

翻译后的段落丢失了一些换行符：

```
测试段落 1
测试段落 2

测试段落 3
测试段落 4

测试段落 5
```

最后得到的结果会像下面这样显示：

```
test paragraph 1
测试段落 1
测试段落 2

test paragraph 2
测试段落 3
测试段落 4

test paragraph 3
测试段落 5

test paragraph 4
-

test paragraph 5
-
```

插件会检查每个合并单元的原文和译文的行数，如果译文行数和原文不一致，会用 `-` 补全。这样就会导致一些连在一起的译文提前显示 。

**Comment by Andy-AO** [comment]
> 是原文丢失吗？按照目前的处理方式，原文和译文都不应该丢失的，否则就是需要修复的错误。如果是感觉译文丢失，建议检查一下译文是否合并到了前面的段落中。下面是目前的处理方式：
> 
> 假设待翻译段落的合并单元如下：
> 
> ```
> test paragraph 1
> 
> test paragraph 2
> 
> test paragraph 3
> 
> test paragraph 4
> 
> test paragraph 5
> ```
> 
> 翻译后的段落丢失了一些换行符：
> 
> ```
> 测试段落 1
> 测试段落 2
> 
> 测试段落 3
> 测试段落 4
> 
> 测试段落 5
> ```
> 
> 最后得到的结果会像下面这样显示：
> 
> ```
> test paragraph 1
> 测试段落 1
> 测试段落 2
> 
> test paragraph 2
> 测试段落 3
> 测试段落 4
> 
> test paragraph 3
> 测试段落 5
> 
> test paragraph 4
> -
> 
> test paragraph 5
> -
> ```
> 
> 插件会检查每个合并单元的原文和译文的行数，如果译文行数和原文不一致，会用 `-` 补全。这样就会导致一些连在一起的译文提前显示 。


检查之后发现译文的确没有丢失，只不过是显示在了原文的前方而不是后方。在之前的时候我没有意识到这个问题，所以我还是在原文后面找译文，没有找到，误以为是没有，实际上是有的。

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/a9d2c3bf-823b-4aea-ac26-e72ed2f52d63)


一会儿出现在前面，一会儿出现在后面，这个对阅读造成了很大的阻碍。我认为这算是一种bug，因为程序设置中我们设定的就是译文在原文后，这种情况出现之后，这个设定就已经被破坏了。

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/bc962cd7-8de5-4bf3-b976-17c8b27a8c36)

**Comment by bookfere** [comment]
是的，行数不一致的译文也应该跟随设置放置。标记一下，后面改进。

**Comment by bookfere** [comment]
在解决这个问题时候又发现一个问题，对于行数无法对齐的合并单元，如果按照错乱的顺序插入（如下方案一所示），还是会失去参照意义。如果一旦行数不一致，把整个合并单元的译文全都放到原文前或后（如下方案二所示），是否更些好一些？

---

译文添加到原文后（方案一）：

```
test paragraph 1

测试段落 1
测试段落 2

test paragraph 2

测试段落 3

test paragraph 3
```

译文添加到原文后（方案二）：

```
test paragraph 1

test paragraph 2

test paragraph 3

测试段落 1
测试段落 2

测试段落 3
```

---

译文添加到原文前（方案一）：

```
测试段落 1
测试段落 2

test paragraph 1

测试段落 3

test paragraph 2

test paragraph 3
```

译文添加到原文前（方案二）：

```
测试段落 1
测试段落 2

测试段落 3

test paragraph 1

test paragraph 2

test paragraph 3
```

**Comment by Andy-AO** [comment]
> 在解决这个问题时候又发现一个问题，对于行数无法对齐的合并单元，如果按照错乱的顺序插入（如下方案一所示），还是会失去参照意义。如果一旦行数不一致，把整个合并单元的译文全都放到原文前或后（如下方案二所示），是否更些好一些？
> 
> 译文添加到原文后（方案一）：
> 
> ```
> test paragraph 1
> 
> 测试段落 1
> 测试段落 2
> 
> test paragraph 2
> 
> 测试段落 3
> 
> test paragraph 3
> ```
> 
> 译文添加到原文后（方案二）：
> 
> ```
> test paragraph 1
> 
> test paragraph 2
> 
> test paragraph 3
> 
> 测试段落 1
> 测试段落 2
> 
> 测试段落 3
> ```
> 
> 译文添加到原文前（方案一）：
> 
> ```
> 测试段落 1
> 测试段落 2
> 
> test paragraph 1
> 
> 测试段落 3
> 
> test paragraph 2
> 
> test paragraph 3
> ```
> 
> 译文添加到原文前（方案二）：
> 
> ```
> 测试段落 1
> 测试段落 2
> 
> 测试段落 3
> 
> test paragraph 1
> 
> test paragraph 2
> 
> test paragraph 3
> ```

在错乱的情况下，没有办法将原文和译文对应起来，因此容易输出错误的对应，所以方案二会好很多，它总是产生正确的对应，只不过是粗糙的正确，粗糙的正确比精确的错误好。

**Comment by Andy-AO** [comment]
测试了下，现在的确会出现，原文和译文无法正确对应的问题
```log
test paragraph 1

test paragraph 2

test paragraph 3

test paragraph 4

test paragraph 5

test paragraph 6
```

```log
测试段落 1
测试段落 2

测试段落 3

测试段落 4
测试段落 5

测试段落 6
```

输出结果是

```log
test paragraph 1



test paragraph 2



test paragraph 3

测试段落 1 测试段落 2



test paragraph 4

测试段落 3



test paragraph 5

测试段落 4 测试段落 5



test paragraph 6

测试段落 6


```
