### ISSUE TITLE
建议实现自定义OpenAI模型名

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#213]
现在OpenAI模型的名称是不能自定义的，这就导致新出了一个模型之后没有办法立即使用。
当然可以使用自定义引擎的方法解决这个问题，但直接提供名称自定义方便很多。
Immersive Translate 就有类似的功能。
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/fb5fd8c8-cb6d-4227-b6c9-dfb61a8c13da)

**Comment by bookfere** [comment]
谢谢反馈。此需求同 #167。功能已在提交 e1bd8fb8cb5d8c265ca6f4fa0eacb8a10fd92308 中实现。如果你是从 Calibre 插件管理器中安装的插件，在新版本发布前，可前往  https://translator.bookfere.com  下载安装最新的 Rolling release 版本使用此功能。
