### ISSUE TITLE
[bug]在没有错误信息的情况下自动停止翻译

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#215]
发现了一个可能的bug，这个工具可能会在没有错误信息的情况下**自动停止翻译**。
1. 我已经将引擎的停止翻译数设置为100，留下了很大的冗余
2. 点击全部翻译之后，翻译了一些内容，但还没翻译完，然后就自动停止了
3. 没有看到错误日志，不知道出现了什么问题

使用的是自定义引擎，调用通义千问，版本是最新的`ebook-translator_20240228224327`。

**提供录屏**

https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/2499131b-8ebc-4a40-b159-a7f741fd83b8

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/13480cd0-4555-4214-8e5b-caf970075787)

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/28604156-a8c4-41b5-9419-a2b9de203ce8)

**Comment by bookfere** [comment]
应该是之前错误的把重试次数当成取消翻译的条件了。安装最新版再试试看。
