### ISSUE TITLE
翻译后输出的文件名不生效

### ISSUE THREAD

**Issue by gnyuan** [bookfere/Ebook-Translator-Calibre-Plugin#229]
翻译后，输入新的文件名，文件名结尾增加`-中英文版`，但保存后仍然是原来的名字。

**Comment by gnyuan** [comment]
> 插件是否安装的最新版本？如果插件是从 Calibre 的插件管理器下载的，请先前往 https://translator.bookfere.com 下载 Rolling Release 版本再试试看。

是的，通过插件管理器下载，已下载` Rolling Release 版`仍然在最后修改文件名不生效。不知道我这哪个步骤操作有问题？

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/6140657/ab12cba7-f80f-4e9d-a6a3-165fd7c05db9)

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/6140657/2b22d35c-480c-472c-ba25-cd29c2dd25ad)

**Comment by bookfere** [comment]
在“高级模式”界面上修改的书名不会写到元数据中，只对在插件设置中指定输出路径后所存放的文件名有效。

**Comment by gnyuan** [comment]
> 在“高级模式”界面上修改的书名不会写到元数据中，只对在插件设置中指定输出路径后所存放的文件名有效。

明白了，个人感觉翻译后的书要么带个固定后缀，要么允许用户给新的名字，不然元数据一样在calibre里没法区分。谢谢啦！

**Comment by bookfere** [comment]
在昨天的提交 c89e7352a1f3d15e2ea0d948ad98672352fed44d 中，新添加了翻译元数据的功能，元数据中的书名会根据你设置的译文位置变成双语形式。

**Comment by gnyuan** [comment]
> 在昨天的提交 [c89e735](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/commit/c89e7352a1f3d15e2ea0d948ad98672352fed44d) 中，新添加了翻译元数据的功能，元数据中的书名会根据你设置的译文位置变成双语形式。

非常感谢！！
