### ISSUE TITLE
翻译docx文件是格式问题

### ISSUE THREAD

**Issue by yonmnm** [bookfere/Ebook-Translator-Calibre-Plugin#236]
**Basic information**

* Operating System: **Windows**
* Calibre Version: **2.3.2**
* Plugin Installation: **From Calibre/Rolling Release**

**Describe the bug**
中文翻译为英文
1、一段文字会拆分为很多段，还会拆分为单个字
2、有自动编号的段落会导出后会把该段落变为表格，原文和译文左右排列

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/88870346/2733cc3e-f2be-4f3f-b889-2d813264f5fe)

**Comment by bookfere** [comment]
谢谢反馈。这可能是 Calibre 的问题。由于插件依赖从 Calibre 的转换过程中提取内容，如果 Calibre 无法正确处理 Word 文档，插件也就无法正确处理。你可以尝试先用 Calibre 转换一遍格式，看结果是否正常。
