### ISSUE TITLE
原文中的引用符号会被直接翻译

### ISSUE THREAD

**Issue by stormeyes** [bookfere/Ebook-Translator-Calibre-Plugin#238]
**基础信息**
epub电子书下，原文中的引用符号比如 “叶卡捷琳娜大帝曾经表态过如何处理俄罗斯农奴[3]的方案” 中翻译后本来是引用的符号 [3] 会丢失其HTML标签属性，变成纯字符串的 [3] 

* 操作系统: **Windows/macOS/Linux 发行版**
* Calibre 版本: **7.6.0**
* 插件来源: **安装自 Calibre 市场**

**屏幕截图**
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/5072174/7a477abd-b1f1-49da-9f8e-a90b5b7ede7c)

**Comment by stormeyes** [comment]
看了以下源码，本质上这些脚注其实是这样一段HTML代码
```
他們踏上了東方的土地，彷彿充滿了當年亞歷山大和圖拉真的感覺。他們踏在烏爾<a class="footnote" href="#fnX-1" id="fX-1">[1]</a>（Ur）的土地上，深切地感到，他們做為基督徒，是「迦勒底的吾珥<a class="footnote" href="#fnX-2" id="fX-2">[2]</a>」（Ur Kasdim）的公民亞伯拉罕在文明意義上的繼承人。
```
我在`设置`中的`忽略元素`添加了两条规则，删掉了缓存重新翻译，好像还是没变化
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/5072174/cfda5330-fe72-46ac-bca0-57cd63ccbd81)

**Comment by bookfere** [comment]
这个“忽略元素”可能会让人误解。它其实是上面那个忽略段落功能的补充，只是可以通过 CSS 选择器匹配而非文本匹配。

你想要的应该是“保留元素”，就像内置的保留 `<code>`、`<img>` 或 `<br>` 这样的元素一样。未来的版本会添加这个功能。
