### ISSUE TITLE
[功能请求] 单换行符的启发式处理

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#243]
合并翻译的译文中不应该出现单个换行，但有的时候的确存在，那么将单换行符替换成双换行符，译文中的格式错误就可以解决。
建议在设置中添加“启发式处理”，其中有个选项是“处理单换行符”，开启之后可以解决自动很多合并翻译的格式问题。

**Comment by Andy-AO** [comment]
可以使用正则表达式`(?<!\n)\n(?!\n)`匹配单独出现的换行符

**Comment by bookfere** [comment]
根据 #148 的请求，未来可能需要用单个换行符取代 `<br />` 元素，以实现换行间的原译文对照，因此不太合适用它区隔段落。

**Comment by Andy-AO** [comment]
> 合并翻译的译文中不应该出现单个换行，但有的时候的确存在，那么将单换行符替换成双换行符，译文中的格式错误就可以解决。 建议在设置中添加“启发式处理”，其中有个选项是“处理单换行符”，开启之后可以解决自动很多合并翻译的格式问题。
