### ISSUE TITLE
[Bug report] 上标以及前面的内容丢失

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#244]
翻译一个epub文件的时候，发现$Na^+$中的$+$丢失

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/8514b4ae-b454-48f0-b3b0-0a6a11717b51)

文件在这里下载：https://zh.z-library.se/book/25448823/ab4018/berne-levy-physiology-by-teamira.html

**Comment by Andy-AO** [comment]
Na+丢失，且之前的内容也丢失了，「FIG. 34.1」没有出现在译文中
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/00e59e90-ff37-49cd-8ffd-57967549e8e4)

**Comment by bookfere** [comment]
试试最新版本看是否解决了此问题。

**Comment by Andy-AO** [comment]
> 试试最新版本看是否解决了此问题。注意，新版本会导致之前的缓存失效。

谢谢。
测试后发现报错
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/f83ccc5a-0110-49f5-89e9-64aa61791087)

**Comment by Andy-AO** [comment]
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/c066133a-1c50-4a51-bd30-5542f86cb830)
报错之后就在这个页面卡住了，一个小时之后发现进度条没有任何变化

**Comment by bookfere** [comment]
新版本已修复了这个问题，再试试看。

**Comment by Andy-AO** [comment]
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/7a2b7647-cd1e-4292-aa6d-c9e038a2bd8a)
问题已解决

**Comment by GoTop** [comment]
> 试试最新版本看是否解决了此问题。注意，新版本会导致之前的缓存失效。

新版缓存和旧版数据库结构不同？
