### ISSUE TITLE
[错误报告] 无法删除缓存

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#246]
**基础信息**

* 操作系统: **Windows**
* Calibre 版本: **7.5.1.0**
* 插件版本：**v2.3.2**
* 插件来源: **安装自 Calibre**

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/5ab65283-6068-463b-b786-42c425d76f52)
在没有运行任何任务的前提下，仍然无法删除缓存。

**Comment by bookfere** [comment]
试试最新版本看看问题是否还存在。

**Comment by Andy-AO** [comment]
> 试试最新版本看看问题是否还存在。

问题已经不存在
