### ISSUE TITLE
[错误报告] 无法加载缓存

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#247]
**基础信息**

* 操作系统: **Windows**
* Calibre 版本: **7.5.1.0**
* 插件版本：**v2.3.2**
* 插件来源: **安装自 Calibre**

有个文件刚翻译完，退出之后重新点开，发现已有的缓存没有被加载，而是创建一个新缓存

# 缓存没有加载
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/303ffce8-ea8a-4188-a4e6-5e498f9f3cc8)
# 缓存的确存在
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/69596a76-29ef-4c74-8e82-5ff476c68b15)

**Comment by bookfere** [comment]
能否把这两个缓存发上来看看？检查一下有什么不同。

**Comment by Andy-AO** [comment]
> 能否把这两个缓存发上来看看？检查一下有什么不同。

缓存已发

[cache.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/14687159/cache.zip)

**Comment by bookfere** [comment]
缓存没看出有什么问题。这个问题能重现吗？打开一次，翻译一条，关闭重新打开。

**Comment by Andy-AO** [comment]
> 缓存没看出有什么问题。这个问题能重现吗？打开一次，翻译一条，关闭重新打开。

我这里现在已经不能重现，可能是我哪里搞错了，不好意思。
