### ISSUE TITLE
[错误报告] 输出文件出现OSError

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#248]
**基础信息**

* 操作系统: **Windows**
* Calibre 版本: **7.5.1.0**
* 插件版本：**v2.3.2**
* 插件来源: **安装自 Calibre**

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/3f10ea80-7abe-47da-b167-222a653df6ca)

图书地址：https://zh.z-library.se/book/27662268/0336fb/female-arousal-and-orgasm-anatomy-physiology-behaviour-and-evolution.html

**Comment by bookfere** [comment]
只是这本书出现这个错，还是其他电子书也会出现？

**Comment by Andy-AO** [comment]
> 只是这本书出现这个错，还是其他电子书也会出现？

目前只发现了这个电子书有问题

**Comment by bookfere** [comment]
试试最新版本看看问题是否还存在。

**Comment by Andy-AO** [comment]
> 试试最新版本看看问题是否还存在。

问题已经不存在
