### ISSUE TITLE
[功能请求] 忽略超出尝试翻译次数的条目并继续翻译

### ISSUE THREAD

**Issue by GoTop** [bookfere/Ebook-Translator-Calibre-Plugin#249]
建议针对条目增加一个“尝试翻译次数”，如果超过这个次数，则停止翻译这个条目，继续翻译后面的条目，而不是停止整本书的翻译

超过“尝试翻译次数”仍未获取到翻译文本的条目，标记一下颜色，这样方便用户手动获取翻译后输入

现在插件的设置好像是“超过连续错误次数中止翻译”，如果某个段落因为太长或者其他原因，总是获取不到翻译，那整本书的翻译就会在这里停止。

**Comment by bookfere** [comment]
提交 f876702cd768f44f1362299d5307f48b39f05346 解决了此问题。可在设置中将停止翻译的尝试次数设为 0，表示不限制次数。
