### ISSUE TITLE
使用自定义的ChatGPT引擎时，是否可以设置文本流？

### ISSUE THREAD

**Issue by GoTop** [bookfere/Ebook-Translator-Calibre-Plugin#252]
插件只有官方ChatGPT可以启用文本流

**Comment by bookfere** [comment]
如果你用的是兼容 ChatGPT 的 API，可以选择 ChatGPT (OpenAI) 并自定义端点。

**Comment by GoTop** [comment]
> 如果你用的是兼容 ChatGPT 的 API，可以选择 ChatGPT (OpenAI) 并自定义端点。

哦，原来在ChatGPT (OpenAI) 可以自定义端点
