### ISSUE TITLE
[功能请求] 筛选合并出错的条目以提高效率

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#254]
在合并翻译完成之后，会有很多行数不匹配的，出错的条目，虽然用黄色高亮了，可是想找到和选中还是很难。
有的时候这些出错的地方分散在上千个条目中，查找需要耗费很多的精力。
希望在UI上添加个筛选按钮，可以筛选出合并出错的项目，以便集中处理，比如手动修复或者更换引擎重新翻译，这样可以大幅提高效率。

**Comment by bookfere** [comment]
列表今后会增加一个搜索/筛选功能，可以把这个需求并入进去。
