### ISSUE TITLE
[Bug report] 错误的分行

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#257]
**Basic information**

* Operating System: **Windows**
* Calibre Version: **7.5.1**
* Plugin Version: **v2.3.3**
* Plugin Installation: **From Calibre**

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/88afbf05-3d79-4a28-9dfb-bbaa7c3d133d)
[123.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/14809092/123.zip)

**Comment by bookfere** [comment]
<img width="818" alt="screenshot" src="https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/29969316/9f541142-dd7b-41ae-a555-867129929092">

这个结构有些奇怪，估计得特殊处理才行。

**Comment by bookfere** [comment]
通过新添加的“首选元素”设置通过 CSS 选择器把特定元素设为优先提取。
