### ISSUE TITLE
[功能请求] 可否选择性翻译？

### ISSUE THREAD

**Issue by ddtoys** [bookfere/Ebook-Translator-Calibre-Plugin#271]
最近遇到一些韩国作者写的学习英语的书，里面的主体都是韩文，示例为英文。
目标：
1. 韩文翻译为中文
2. 英文保持不变

尝试了翻译中设置韩文→中文，但依然把所有文字都翻译为了中文，不知道是不是我设置的不对还是默认英文必须翻译为中文等功能闲置

希望有个识别文字并翻译的功能

**Comment by bookfere** [comment]
可以尝试在高级模式中在英文条目上点击右键，看通过“选择相似条目”菜单是否能选中所有英文条目，如果能的话可以将其删除。

如果不能，和 #262 一样，需要优化段落排除后才能解决。你也可以把样本发送到书伴邮箱（见 GitHub 资料页）以便测试。

**Comment by ddtoys** [comment]
> 可以尝试在高级模式中在英文条目上点击右键，看通过“选择相似条目”菜单是否能选中所有英文条目，如果能的话可以将其删除。
> 
> 如果不能，和 #262 一样，需要优化段落排除后才能解决。你也可以把样本发送到书伴邮箱（见 GitHub 资料页）以便测试。

收到！我回来测试一下。刚刚准备尝试结果发现z-lib挂了，哎，之前没download就是因为解决不了选择性翻译，现在倒好，想干活了，找不到书了。等尝试的时候一定第一时间反馈一下，多谢大佬！

**Comment by ddtoys** [comment]
> 可以尝试在高级模式中在英文条目上点击右键，看通过“选择相似条目”菜单是否能选中所有英文条目，如果能的话可以将其删除。
> 
> 如果不能，和 #262 一样，需要优化段落排除后才能解决。你也可以把样本发送到书伴邮箱（见 GitHub 资料页）以便测试。

哇！成功啦！感谢感谢！
临时找了本别的韩语的英语学习书，按照你说的方法删除了类似，然后翻译剩下的，英语例句都保留了。
![Snipaste_2024-04-08_09-32-16](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/101969659/8a87702a-b672-4f03-9af8-10cf94ef5420)
最后一点点一点点“鸡蛋挑骨头”的就是，类似混合输入的，我速速找了一个地方，如图，有的地方就把韩英混合中的英文翻译了，有的就没有翻译，不过这种混合输入的想必真是高难度了，整体例句翻译已经惊艳到极致了，再次感谢！
![11](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/101969659/cfa511d1-5f17-4cde-929e-7760f9385eb4)

**Comment by bookfere** [comment]
客气了，这不是“鸡蛋里挑骨头”，而确实是需要改进的地方。同 #238，插件将会添加一个手动指定保留某些元素的功能，以保留不需要翻译的元素，比如截图中的 code 和 target 这两个单词。

**Comment by ddtoys** [comment]
真棒！
