### ISSUE TITLE
[功能请求] 对于合并翻译被标黄的项增加再次重试的按钮

### ISSUE THREAD

**Issue by Arthur-WWW** [bookfere/Ebook-Translator-Calibre-Plugin#276]
对于合并翻译后译文段落数对不上的分段，现在已经被标黄来提醒用户，能否加一个再次重新翻译所有标黄分段的按钮，我发现再次翻译后有很大概率段落数就能对上了，现在我是手动这样做的，但数量一多手工选起来就比较麻烦，而且有时也需要重试好几次或换不同的模型重试。为了提升翻译质量合并翻译还是很有必要，否则对于一些很短的段落，比如只有一个人名这种段落模型会返回一堆莫名其妙的内容，合并翻译后有了一定的上下文就可以避免这种情况。

**Comment by Andy-AO** [comment]
现在已经有筛选全部未对齐条目的功能，你可以升级到最新版本，就可以享受该功能。
筛选之后Ctrl+A全选，然后点击翻译选中项目即可，不需要手动完成。

**Comment by bookfere** [comment]
补充一下，筛选后手动全选不是必须的，点击【翻译全部】按钮只会翻译筛选后的结果。

**Comment by Arthur-WWW** [comment]
试了最新版完美实现了想要的功能，这样处理没对齐的就方便多了，非常感谢感谢
