### ISSUE TITLE
[功能请求] 为常用按钮添加访问键

### ISSUE THREAD

**Issue by Andy-AO** [bookfere/Ebook-Translator-Calibre-Plugin#277]
常用的按钮「保存」，在很多程序中都有类似Alt+s的访问键，可以用来快速点击，提高效率，而该插件目前没有快速访问键，想要添加一下。

很多GUI用`&Save`、`保存(&S)`命名就可以自动实现，Qt或许也有类似的功能，如果是这样则并不困难。

**Comment by bookfere** [comment]
感谢 PR。是不是使用 [QShortcut](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtwidgets/qshortcut.html#) 和 [QKeySequence](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtgui/qkeysequence.html#) 这两个类会更灵活些？PyQt 也提供了一些标准快捷键（[Standard Shortcuts](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtgui/qkeysequence.html#standard-shortcuts)），可以同时兼容多个平台。这样不需要依赖字符，也不需要更改多个翻译文件，想自定义快捷键也容易改动。

我刚提交了一个简单的实现，把 Alt+S 改成了 Ctrl+S，快捷键没体现在按钮上，只是以工具提示的形式出现。

**Comment by Andy-AO** [comment]
@bookfere 
谢谢
1. 用下划线体现在按钮文本上，好处是直观，不用去想按钮对应的快捷键到底是哪个，坏处是多语言处理起来麻烦。
2. 不清楚该功能是否兼容多平台，如果不兼容，还是用Qt的机制比较好。

**Comment by bookfere** [comment]
[QShortcut](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtgui/qshortcut.html) 文档对助记符号快捷键用法包括兼容问题做了说明。可以看出，唯一的区别是是否为字符显示下划线。Windows 系统可控制是否显示下划线字符，而 macOS 需额外启用这种快捷键，且不会显示下划线字符。

> In widget applications, certain widgets can use ‘&’ in front of a character. This will automatically create a mnemonic (a shortcut) for that character, e.g. “E&xit” will create the shortcut Alt+X (use ‘&&’ to display an actual ampersand). The widget might consume and perform an action on a given shortcut. On X11 the ampersand will not be shown and the character will be underlined. On Windows, shortcuts are normally not displayed until the user presses the Alt key, but this is a setting the user can change. __On Mac, shortcuts are disabled by default. Call [qt_set_sequence_auto_mnemonic()](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtgui/qtgui-module.html#qt_set_sequence_auto_mnemonic) to enable them. However, because mnemonic shortcuts do not fit in with Aqua’s guidelines, Qt will not show the shortcut character underlined__.

如果要加这种快捷键而不修改翻译文件，用第二种方案比较合适（不同语言用不同字符应该没必要）：

```
save_button = QPushButton(_('Save') + ' (&S)')
```

我只记得曾在菜单中用过 Alt+X 这种快捷键，很少在按钮上用。不知道是否是个人习惯，想看看其他人意见。

**Comment by Andy-AO** [comment]
@bookfere 
估计每个系统有不同的习惯，感觉在windows上，习惯给一些元素添加助记符快捷键，比如选择框、选项卡、菜单、某些按钮。
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/989ba332-1e5b-41f0-a1b1-a0e9c8121160)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/e5725146-07d8-468e-ae20-06b981874fb3)
![image_1354](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/b105b52b-3c49-4258-8eff-6edd8b02d95b)
![image_1355](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/749b6c9a-6a9c-4961-977b-e40b55035a7e)
![image_1356](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/0d3e36eb-6551-4d63-895f-d8c95456368e)

**Comment by Andy-AO** [comment]
根据我搜索到的资料，在软件国际化的过程中，助记符应该跟随文本，而快捷键则应该保持不变。

如果语言不使用罗马字符，那么才会在标签后用括号标出助记符。

测试之后发现的确如此，比如Windows上著名的文件管理器，改成法语之后就采用法语首字母作为助记符

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/b1eb112c-2722-494e-a8fa-8dbc583ecaeb)


![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/38101170/bb5431df-5515-41ea-aa19-c5c99fce8a3a)

**Comment by Andy-AO** [comment]
@bookfere 
我的想法是，标准的快捷键对于涵盖在内的场景的确很有帮助，可是对于很多与之无关的按钮还是需要额外处理，这个时候至少在Windows和X11上助记符还是个不错的方案，如果Mac上没有下划线了，那么意义不大，可是支持下无妨，因为如果没有，也不会有什么坏处。

**Comment by bookfere** [comment]
根据[快捷键的介绍](https://en.wikipedia.org/wiki/Keyboard_shortcut)和上面的讨论，快捷键不受本地化影响是统一的，而助记符号需要依赖本地化字符。我之前没太弄清楚这两者的关系。给有使用助记符号习惯的系统添加这种用法是合理的。助记符号需要依赖本地化字符，更改语言文件也是合理的。
