### ISSUE TITLE
Possible to translate larger sections at a time?

### ISSUE THREAD

**Issue by armyofgnomes** [bookfere/Ebook-Translator-Calibre-Plugin#28]
Is there a way to translate larger portions of the text at once, rather than line by line? It seems like the translations would be more accurate if there is more context available, particularly for the ChatGPT option. 

Dialogue especially can have issues because the translation engine doesn't know who is speaking or how the line works in the context of the full conversation.

**Comment by bookfere** [comment]
To translate a specific (larger) number of characters at once, you can enable the "Merge to Translate" feature. If you are using an older version without this feature, please update to the latest version 1.3.2.

<img width="594" alt="merge-to-translate" src="https://user-images.githubusercontent.com/29969316/235654788-d5d8d658-5fae-4b38-8eaa-ad62209dd3da.png">

**Comment by armyofgnomes** [comment]
Excellent, thanks!
