### ISSUE TITLE
[Bug report] docx文件，翻译后目录丢失严重。

### ISSUE THREAD

**Issue by Benson1997** [bookfere/Ebook-Translator-Calibre-Plugin#283]
**Basic information**

* Operating System: **Windows**
* Calibre Version: **7.5.1**
* Plugin Version: **2.3.3**
* Plugin Installation: **From Calibre/Rolling Release**

**Describe the bug**
docx文件，翻译后目录丢失严重。（文件是通过foxit把pdf转成docx的。）

源文件：
[bug-译后目录丢失严重.docx](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/14996911/bug-.docx)

**Expected behavior**
希望翻译后，能保留目录。
不过word的标题导航，好像是根据正文中的标题样式来，还是分行显示比较简单些呢

**Screenshots**
![图片](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/6b238b81-b585-4b1d-b8b9-94cc05acabe8)

**Comment by bookfere** [comment]
建议先用 Calibre 转换一遍，看看目录是否正常。插件完全依赖 Calibre 的转换结果，如果 Calibre 没能很好地还原文档原来的结构，插件也就无能为力了 :(

**Comment by Benson1997** [comment]
好的，感谢老大的回复，确实是calibre这边的问题。问题不在插件上，希望以后更新能解决这个问题吧。🤞

![图片](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/49bafd72-0373-46f0-90cc-d06a5aea1f4e)

**Comment by Benson1997** [comment]
通过在word中 重新点一下，标题1，标题2，标题3的样式，目录就可以完整兼容了。
（估计是通过软件转换后的标题样式，掺杂了一些其他信息，所以calibre在识别的时候出现了一些错误。）

算是简单重定义一下标题。😁
