### ISSUE TITLE
Calibre ebook translator does not write output file [ 

### ISSUE THREAD

**Issue by johndelaneycrowe** [bookfere/Ebook-Translator-Calibre-Plugin#285]
**Basic information**

* Operating System: **Windows 10**
* Calibre Version: **7.9**
* Plugin Version: **2.3.3**
* Plugin Installation: **From Calibre/Rolling Release**

**Describe the bug**
Translating a single epub to epub using Google Free, translation appears to work with no errors in the log but does not write an output file to the directory specified in translation settings.

**Expected behavior**

**Screenshots**

**Comment by bookfere** [comment]
Which method did you use, Batch mode or Advanced mode? and how much time was consumed until the translation was completed?

**Comment by johndelaneycrowe** [comment]
Thanks - I have solved the problem i I wasn't clicking thee output button
after translation

regards,
John
