### ISSUE TITLE
[Feature request] Glossary Editor - Import-export- BiDi RTL

### ISSUE THREAD

**Issue by drkhateeb** [bookfere/Ebook-Translator-Calibre-Plugin#297]
Hello dev
Kindly add these features:
1-support to set RTL BiDi function for Arabic in output Translation
2- Add Arabic to DeepL - it is now available
3- Add a form to (add- remove entries to glossary - import- export from excel-csv, txt TAB)
4- save edited translation in TMX or other formats for reuse
5-add MyMemory to MT engines (https://mymemory.translated.net/doc/spec.php) and set save function to store edited translation
6- add Lingvanex (https://docs.lingvanex.com/reference/overview)
7- Export the output translation as facing Page by Page (odd pages for original - even Pages for Translation)
8- set RTL BiDi in Translation Editor.

Kind Regards

**Comment by bookfere** [comment]
The first requirement has been addressed in commit a5d219cf9d352cc9cb13436aeee0ef19a56bcbad. You can check it out by installing the Rolling Release version.

Other requirements, except for 4, 5, 6, and 7, may be implemented in future versions.

Regarding the 4th and 5th requirements, the plugin stores translations in SQLite format, and you can modify them in Advanced mode or using other SQLite clients whenever you want.

Regarding the 6th requirement, I recommend leveraging the custom engine feature for your specific needs.

Regarding the 7th requirement, if the translation is appended next to the original page, how can you conveniently check the translation against the original?

**Comment by drkhateeb** [comment]
Thanks for demonstrations
Kindly take a look at the new design of the translation editor

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/161371/9153166e-2830-4e02-b646-fef2e8df04fa)

**Comment by drkhateeb** [comment]
Functions:
1-	Add doc and extract text as Paragraphs/chunks to Source coloum
2-	View /highlight terms based on the Terms List
3-	Translate using NMT/AI engine (Textra NMT, Deepl, Google, Yandex, Lingvanex, Gemini Pro) using Term list
4-	Proofread by AI for spelling, grammar, spacing, etc,
5-	Rephrase by Gemini-Pro (or GPT4, etc,)
6-	Diacritic the last letter of Arabic words (optional)
7-	Export Doc as final Target- or Bilingual  ()
8-	Export Translation as Excel/TMX for sharing
-	User can Translates and  (rephrase, diacritic, proofread) segment by segment, or
-	Translate (or rephrase, diacritic, proofread) by Batch, by selected segments
-	Export to Excel 3 (source, target, rephrase) or 2 columns (source and rephrase)
