### ISSUE TITLE
原文输入错误

### ISSUE THREAD

**Issue by 13879885572** [bookfere/Ebook-Translator-Calibre-Plugin#3]
有一个小问题，翻译日语书籍时，会连同ルビー（注音）一起翻译。
如（书名号内为ルビー）：（原文）希《こいねが》うその言葉には、幾ばくの思いが籠められていたのか。（译文）Koinega的话经过了多少深思熟虑？
另外，可否添加有道或百度翻译？谷歌翻译太慢了，chatgpt收费，而deepl注册api需要一张国外信用卡）

**Comment by bookfere** [comment]
抱歉不懂日语文法，书名号《》在日文中是专门用来注音的吗，不会有其他用法吗？

**Comment by 13879885572** [comment]
抱歉我说快了，我输入的格式是epub，epub是支持日语注音的，注音方式和我们的汉字注音一样，横排版的话用小一号的字注在汉字上方，竖排版的话用小一号的字注在汉字右边。而txt无法这样注音，一般用《》表示，青空文库（一个日本的公版书网站，像夏目漱石宫泽贤治芥川龙之介等等作家的书都能免费阅读）也是这样标注的。据我所知，在日语正文中，《》很少出现，引用一本书她们也不用这个符号。
另，我的日语是自学的，可能出现一些谬误，您可以咨询更加专业的人士。
最后感谢您，这个插件太好用了，对我有很大帮助！

**Comment by bookfere** [comment]
谢谢补充信息。这样的话，对于日语书籍可以把《》中的内容抽离出来，等翻译完成后再还原回去。之后的版本会尝试解决这个问题。

**Comment by 13879885572** [comment]
是的，如果是TXT格式的这样就行了，其他格式应该还是不行。我试了一下，把其他格式的一句话复制到TXT文档，会呈现以下状态（还是用之前那句话举例）：
epub复制到TXT文档：希こいねがうその言葉には、幾ばくの思いが籠められていたのか。
docx复制到TXT文档：希(こいねが)うその言葉には、幾ばくの思いが籠められていたのか。
复制之后它们都不是《》

**Comment by bookfere** [comment]
如果方便的话可以发送一个电子书样本到书伴邮箱：bookfere@gmail.com

**Comment by 13879885572** [comment]
http://xisang.top/
这个网站是已经转换成epub的青空文库的小说，您可以按需求下载

**Comment by bookfere** [comment]
![sample](https://user-images.githubusercontent.com/29969316/229139319-4910fb6d-4a79-4b33-a948-bf1b01086ce9.png)

明白了。这种注音都放在 `<rt>` 元素中，处理的时候将其抽出不翻译就可以了。

**Comment by 13879885572** [comment]
是的，就是这样，麻烦您了
