### ISSUE TITLE
[Feature request] A way to activate or not the translation of the book title

### ISSUE THREAD

**Issue by yhngr** [bookfere/Ebook-Translator-Calibre-Plugin#301]
I can't find a way to get the title not translated into the language wanted.
For ex : The original one is the english and the top one in french, but I want to keep the title in english ( just the content need to be translated )
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/76868555/84b9010a-eaaf-4a7e-ab82-9b548f3ab7d8)

**Describe the solution you'd like**
A case where we can activate or not the title translation

**Describe alternatives you've considered**
I've tried to ignore some keyword..etc like docTitle, Title...etc  but nothing work ?

**Comment by bookfere** [comment]
The feature will be added in future versions. Until then, you can simply delete the item using the context menu to ignore translating it.

**Comment by yhngr** [comment]
Okay I see, is it available in the mass translate and not the one per one ?

**Comment by bookfere** [comment]
Not yet. I will add an option to enable or disable translating the metadata.
