### ISSUE TITLE
能否增加一个火山翻译？

### ISSUE THREAD

**Issue by taylormao** [bookfere/Ebook-Translator-Calibre-Plugin#31]
经过我的个人使用，我发现字节跳动旗下的火山翻译的准确度是最最最高的。

**Comment by bookfere** [comment]
谢谢建议。想要测试火山翻译的 API 必须提交敏感信息进行实名认证，因此不太想添加。插件提供了自定义翻译引擎功能，你可以尝试通过其 API 文档提供的信息进行设置，看能否满足需求。

**Comment by taylormao** [comment]
非常感谢

书伴 ***@***.***> 于2023年5月4日周四 20:56写道：
