### ISSUE TITLE
官网api调用报错，以及不知道第三方中转的api是否支持

### ISSUE THREAD

**Issue by hanxiao28** [bookfere/Ebook-Translator-Calibre-Plugin#316]
最开始买了第三方中转的open ai api报错内容是：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.openai", line 92, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 287, in _mech_open
  File "mechanize\_opener.py", line 193, in open
  File "mechanize\_urllib2_fork.py", line 425, in _open
  File "mechanize\_urllib2_fork.py", line 414, in _call_chain
  File "mechanize\_urllib2_fork.py", line 1283, in https_open
  File "mechanize\_urllib2_fork.py", line 1240, in do_open
urllib.error.URLError: <urlopen error _ssl.c:989: The handshake operation timed out>

和报错2：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.openai", line 92, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

{"error":{"message":"Invalid URL (POST /v1chat/completions)","type":"invalid_request_error","param":"","code":""}}

后面找了一个官网的api，然后报错是：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.openai", line 92, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 405: Method Not Allowed

以及
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.openai", line 92, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.pow-button{background-color:#0051c3;border:.063rem solid #0051c3;border-radius:.313rem;color:#fff;font-size:.875rem;line-height:1.313rem;margin:2rem 0;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff;cursor:pointer}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}.rtl .heading-favicon{margin-left:.5rem;margin-right:0}.rtl #challenge-success-text{background-position:100%;padding-left:0;padding-right:42px}.rtl #challenge-error-text{background-position:100%;padding-left:0;padding-right:34px}</style><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "openai.com",cType: 'managed',cNounce: '3825',cRay: '88797d581a4c67f1',cHash: '4246fd78d87eb17',cUPMDTk: "\/api\/?__cf_chl_tk=7nMmF4Hj.EEd8O4sf205Hgdv2V8GtXiLkS3.E__hTgk-1716346131-0.0.1.1-1578",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/api\/?__cf_chl_f_tk=7nMmF4Hj.EEd8O4sf205Hgdv2V8GtXiLkS3.E__hTgk-1716346131-0.0.1.1-1578",md: "Hb.kLAhXRDrOiDGaMQ05VTWqrRh2dexkc4mxIc.xeEE-1716346131-1.1.1.1-csnjF8TdHQuq0EAs.zHSLzHjeJCskOOyrSc5kSWQB8Aeq1quXlu8vWHBRY1IEF_0tnb6U4GZlgTihxFgEHHex7I97buPGVKYQAZ2Xn6v02SHiuSOpmMq6hqnT9jgQjTHxIV48xEQOHGLhe0yxM8PGyMKSQcgIdyGzNnHxx8TatPO8ZmXZXXWqd.3K4UXTsd_pAkG4.6DRjvuB_8qwIR9sZi7GZhVHvAQMLcga.7zwf_F22cvfhcGmHi0E4tbJSyzDzMWr73Vr2gfLsuZ_j5oWvlUxI2S_7e_6OKvXkvBDh_bqRt2OoKUG90e1b4tSf.xIPoXDUNL40Dc60jaWBTno.oYGwoaQVLMyM2bWAdt7G7C8MlhuMlXaF4EZsSPLWUv3yqVCr4.4mq_qOuKA6tq_AW3WzOz_JuqcaFYW1PyRq6DbvalgONgcizowJfwRSvlHYxraklF99wm6u1z7QvfxChtXHxl4uczm95aue3z3ojKcrrpE6rmUmNR5U_DSXFUtcWQbZYbc4J6EtVcIjZcagavjNDvcxSraEcjLn2HgP5Y3fnPgkKrI257ZX2yYeBKpaB0sehnJo_8EYSQdFPcYxxuqZ3KoOwKXFT5iR_w2zuC3JcAWOV2oOVkgkGbIf6V84tuMe0dR9EtmEC25SIqHEILGDbMOOzydDUPx7g_M2vndyVHsS3kZmfvNyqTR7cPSJZI9JQ9jX.9ymNgUpUaXDJvPKdafQ44jfw9MYNwfthfYah.aFgprLn0UorgPLbudn.UMzY0DiC1uUyC1jnjqLd7Tam9NrarueGqYYvNeEAeqnxCXlXYfm_Lw1NJNeyeHQV0rVYyO8yEdgi9u6P4p9CBh7WC1IRNIUK_Bcx6qrUWWGqwGUhKkurtteqoWhIsDith0U2coK7Psb8clX1_1sAob_m8GpV.47qI39Kh0_A.55.bzTUUsOwA0eaMeUwhMwgJZNYi8_K1yrT6TIUP98D9LoWx8YSyLoABnO7o76bdirhWovfWE47je1_wRAG3rqPl93Av96dpqiceqHWcXsMUbyg3gvov3Z.okEzv6DqxkbEejYq_GcnxZ8nCExndSmmHmPJawIh3qeSVRMjwFZXvirSZyuxCHvWL9wV3D15QoHXKIoDXPqXK0yOVVVHLZ.MJNmYfli1Tt_ydYyWeTWKfgdo48wSNpQkxY3MA84wwTjM0EuXasfHUGOUTIgtOWtQd1DIsC5YP1lJois_dV17.dUZciuLRVi.qE.jD6ecvua5Oh14IVecAhtxTlCLw_wifRN_p0zTsuv3hWWdaVjkGk2CAvqeg33Pt.AsgYKmJy0q6yoh4GskAyHk49Kq8B7iI09JqpHId87BsqaR7NYxmWGEUT4IFa7BnKcqBby4RW02cegBOBtW_spqD6NzNqowdtuLYBigy8yrKKSv3pN7exlrmQlOPPrO8eBLFgchca41Mcl_zFSwkZNRcX7CUl5yGYxdAwsGVoSIJmAo3h2sRQtbblYMfYowcV8QvYsU",mdrd: "slKKLjRR7FmtDtUojHrxZwMyASORvAzERhll5Tdd_Y4-1716346131-1.1.1.1-zDmShZPKtziEIAtZ6zPHriwN.LNFP8YutHNUb3yrZufo_acrWyeqzkXDiB7_Qyb3zi4Q9rDyfZk3iPaJop5rYvjbsjpOYKx_4gjPdAjvErC_gHNW4ImNrDdoA9wgMw9QPSgVV9SWn4EOWlxYBSD9TkVmXA9pUaIc57jEL0fDhfzQn_N.Y8o58q.uJ2D2Oab_iHcPspAGeViIfgqGsyss.P6x7mm7Wf5psNdb7lfHnrUCqaln8kmvWQUdq02oLjfuLMmxOGIUApJ1C00bxmXrucxYdGhIWPvGEsio3P4_FyXJ3Ey3QzVLWxY95H3dhrOECTLQFvXPZJzs1UTU6M3rjzMrQ6dugiioQ4c4oyIxMGUKHrgyRpknKtfIa85dR3y6NRdUl7T5DR43LMIFcIFLpqcu6THXLelxcuWiTI5IqR0KcYwwDTr7vjOZt1jnRgLfD9QMJRF9kN63esARY1.IBCzeFeUSiesW.PDLEUQirKem_w1WchP7G7wzdxsj7TaUNFkIrBnCmuByZgtLMaaQPK1Vsmf8ibf0p_l3e2kCiRvZbcECHTTIvg.l7NpYnV_ATW8pyeEB4jncV_6301Exr0fIlo579eQsHybat7fvXA1TuMLL17YXPEmHqVHg2aucMfR7wchIlJ14f7PQXF8W.kqivz7VNUDfJ_hmOZ5Oj0IU3QgfP2NAN9f5tHnRlrtoCnwHoyqBExdyxM0P2tw6_ULQ1zOvuSkpV8h9.q8.98c6rrSHv0oGqqwm1Ueb03zvJ5urlCyyDh2m90yrgXdFn86TpI2cRCItOh3GrfvOp8MCP4xonqZdJwQv3aqOMCAKb0ipsMYWw3pKGKF_iGpzubVQS70W1pdW5jZ0YDbqR1oEz4659InwEfAG7HFW5aTiJn9Ocg5xG8bwgq4yqEyqSwPwm237WHtfBzD.zMOkBeqUveB33QZNRWNqcvFm4lkJDQgdV7ChfKsmuk33AvCvgJ1F2okb6HvzmCra6_xf.ertlb8K7qTPO0HUrgKShrbx5duEW2zuIc9KZcGowLL0LUls3gIjzUgcZQG0J3Y6R7n3bsmGpkalK9u0mp3gn8Prb9QtICBuG7zrSJG.cTIH47lR9qgMm3I8jj8JgNfo7Kr_oZ5g5vrKvB.n91GgwTbIQxgG302oPrQWxkGHVhrQHvKVjnl8GVd8uhTCmsqOFzoyrxjPzQtCEj3XxOYNp.Vy24R55xbcCWHiqdU3.ITONdFy9xNXF69Id21jPGmEdNiG4ErfWf.UfQBJFsOR6MHpNFqUYZu2Aj3t_mvvrGyGwvm0Mma2Pwwm8vUg9r9Tm9p0s5EhmDI2XXHFZPsGI86KfaI2E002LOwkV895PzU6LU8NB6va100CMfZ.64q8DrfS6XySPZ_SzUXERdbsue6Ve5kw25PSa7N8sG_5mD57gzbtdNS6wqcSjVkJLVY7dpGJOXfapRf2R8EBbvZQ2YFwu.HBbjKiphwyefdQAzBlJAeFHCX7.N528pprPef_b2EhKEH33S.fw9X5ZmRTSr3nrr3tBtBFGc5qWe0WQ4Vg1aCvkQ.iYRIp5uytiUl1kCRK5DeFoP.Md91a4D9ozos_kOCICFxl4lOw0XlpuAkxb.1c0Ir8g3vsn4UGLZ1lq.hDdYAYuK14zCJDM.ssdon_doIT_sboNpaKCr3WEMHciM6I_HsJjUMVFRR0etZivZ97.oDDdJJr2ZA4Okf0_6AlJE5ca5aynHCMR9C2J4NO5hEPX7BgGd2rImMDYwShsfrPw8IAIYZqMGdZgN5fDR9Blub0Ua2dNURsLf85tLhclvyj4ZNqg9SWJR5nZICw43363mdVyaGSvgUVqitmTHgOyp2ldkrgge6BiXPxhduswSIMlx.Krvr8WD8wc0UWpoZqBJQP_iMudXlNaQCIUE5NbhWVp.m6CFU0bgZebMem8ptero2_00RsxcoE6puzKU3koFXgTQPO0d3e6fMkqUEyJGzvV2ERt09m8T3_vSOCu39hAp4Fu_22SA9_VhXEpHGzYtr8Y517uNgN_nItZ88ooDiHWQDEsqHBooi4SSDWXj87BM04ydVtp.M4x91ipHTHLTdN8EwpB_rbj6aqwFTtNEVl2oxML.L7WemHV1unRuzZL.62IeeLNzKXj2.iBEuHkMprHjQaCsIJ4TMcxk29mUTxU8gbH_3W_E8ujj6q3KaNOCzntIj3dkpelGbkVLcand5B9Lq3OijizLHJUzFTsRnvSMKj3HzHYERboRXY_0D80onFqoQ3YU51bHk2SUXyls68fvxlVm_BwiOYoF3tLZ7fwnfv3U6tiEmQlSbWT8AsRyu4b0AJ6bnqCmjYgGTNuS3sXS9ZDCAJu5_1VdfQxp6XFfOsVJmeuLz3nkdzEUtvsxED3FVWc1d8oOhXNUdZWe8OSPNKbkgirmZVuAEZ1cyjtATHg.4U9855QEa7XMj1EQiYyOJlZH8XosM1clnGGIQT0IsPRBQhTJor5QIt",cRq: {ru: 'aHR0cHM6Ly9vcGVuYWkuY29tL2FwaS8=',ra: 'RWJvb2stVHJhbnNsYXRvci92Mi4zLjQ=',rm: 'UE9TVA==',d: 'V7nIZ7c6rMOGlD1XXatUvSb/ovHf4hhPDSLtfq2T7cn90wRe5Xqp0k80O0rrkp24N/Hx+6h9XdGUwSTJLQDZBSCfdMEFAG6fEcLmFM/1V9o7KFTYzHUYt8yI+mkM5741Rvrzf3dA2xc718xI19c4H6GyFWmgQPmXSYt43thNnDXThaj+tigr9vAkPNBR/lpFhajHWICJyD3e/pSa7L5nXn7IlTPAxbf6pQCOPXVNSn3r4Ax6+e9GkZdauF67ox0LYQQ4PXk+/5AbGMG8kCULh3aBjyl5PfRmD4I7Y93aljsKnvDRCkz6yI74utevONbZ+HvfLI6SDmpCGLkWqgVo5Ahl/m43n9PGgXhq558LfigxcSAyIlsW8XswfzUX5FzgQPnyLbVQsxTHn75tJQizR5B9YF2at6+rKcfpgK8TeTkTT3QSYRA2f3DbNXatx7LqCFM+W/xsE8RIupT1F/C/d9JngeS9f7eIjru7HG3X6jbJhDDRP4p0bcY4YiSoMpzR5gu8f6/+nNHD9OW2Wso7mXlE8WrJNtemgTc6d2C0tOo=',t: 'MTcxNjM0NjEzMS4yMTgwMDA=',cT: Math.floor(Date.now() / 1000),m: 'LnFMWlj+p3yReMXreD1/WaKXDG+rE6liTnn+WopN8KM=',i1: 'TpUC/0ejw3DdgsIKuWn2Ew==',i2: 'QHtOX1jB18q30kg0+o5xng==',zh: 'ULytyqbUhvezGEhuw7JA3nyKKR78rFU1sFNg5+21X6c=',uh: 'BkoyKAqrBUSweiRIFgUXW0KDznAHxuZldlLXm1q7GIk=',hh: '6DRP17hjzkUmXKzJAms7bA4OqyZ1RY8MCcH+VDleInA=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=88797d581a4c67f1';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/api\/?__cf_chl_rt_tk=7nMmF4Hj.EEd8O4sf205Hgdv2V8GtXiLkS3.E__hTgk-1716346131-0.0.1.1-1578" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

**Comment by bookfere** [comment]
应该是设置的 API 端点有误导致的，参考 #123 检查一下。

**Comment by hanxiao28** [comment]
已设置成功，感谢老大！

**Comment by zlchs1312004** [comment]
> 已设置成功，感谢老大！

我也遇到这个问题了，请问你是如何解决的？我按照前面你们说的都试了还是不行，google free 可以，涉及API的不行
