### ISSUE TITLE
[Feature request] 请求放开并发翻译文件数量的限制

### ISSUE THREAD

**Issue by Benson1997** [bookfere/Ebook-Translator-Calibre-Plugin#320]
您好😁，我在Calibre设置了更大并发数（20），但是好像是 Ebook-Translator-Calibre-Plugin 内置设置了最高上限（12）是吗？

希望能放开这个限制，对于有些速度不快模型，可以通过更多的并发进程来缩短整体的翻译时间。🤞

![图片](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/e67faa9a-b83a-4b37-ac68-158fd4e7aad8)

**Comment by bookfere** [comment]
你需要在 Ebook Translator 插件的 【设置 > 引擎 > HTTP 请求 > 并发限制】中设置并发数量。

**Comment by Benson1997** [comment]
> 你需要在 Ebook Translator 插件的 【设置 > 引擎 > HTTP 请求 > 并发限制】中设置并发数量。

插件里面并发这里设置的是20，但是好像最多并发只有12个，不知道为啥
![图片](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/111626633/1ad1b54a-d759-4861-87ae-3d265769f26e)

**Comment by bookfere** [comment]
原来你指的是并行任务，这和插件的设置就没关系了。会不会和勾选了“__限制最大并发任务数为可用 CPU 核心数__”有关系，这可能会让你上面指定的那个数值失效？

**Comment by Benson1997** [comment]
> 原来你指的是并行任务，这和插件的设置就没关系了。会不会和勾选了“**限制最大并发任务数为可用 CPU 核心数**”有关系，这可能会让并行数量与你的 CPU 核心数相匹配，从而导致上面你指定的那个数值失效？

对对对，怎么没想到是cpu是12核，哈哈，感谢
