### ISSUE TITLE
[Feature request] 번역된 파일명 저장시 언어를 선택할 수 있게 해 주세요(설명 없음)

### ISSUE THREAD

**Issue by summ1055** [bookfere/Ebook-Translator-Calibre-Plugin#322]

**Comment by bookfere** [comment]
The feature already exists. You need to navigate to the settings of the plugin [Settings > Content > __Ebook Metadata__], then check the "__Language Mark__" option and save it.

If I misunderstand your meaning, please provide more details about your requirement.

BTW, I suggest you provide feedback in English as I do not understand Korean. The Korean version reply is automatically translated by ChatGPT, and I hope the expression is accurate.

---

기능이 이미 존재합니다. 플러그인의 설정 [Settings > Content > __Ebook Metadata__] 으로 이동한 다음, "__Language Mark__" 옵션을 선택하고 저장해야 합니다.

당신의 의미를 잘못 이해했다면, 요구 사항에 대해 더 많은 세부 정보를 제공해 주세요.

참고로, 한국어를 이해하지 못해서 영어로 피드백을 주시는 것을 제안드립니다. 한국어 버전 답변은 ChatGPT에 의해 자동으로 번역되었으며, 표현이 정확하길 바랍니다.
