### ISSUE TITLE
[Bug report] 自定义翻译引擎的名称带有.时无法保存并发限制等设置

### ISSUE THREAD

**Issue by xfrose** [bookfere/Ebook-Translator-Calibre-Plugin#323]
**Basic information**

* Operating System: **debian-testing**
* Calibre Version: **calibre-7.12.0-x86_64**
* Plugin Version: **v2.3.4**
* Plugin Installation: **From Calibre/Rolling Release**

**Describe the bug**
自定义翻译引擎时，如果在`"name": `的值里包含了`.`这个符号，就无法保存HTTP请求和中止翻译这两项的所有设置，去掉`.`后就正常了。

**Comment by bookfere** [comment]
谢谢反馈！这个问题很早就有 #78，现在才察觉问题所在 😬。修复后的版本请通过 [Rolling Release](https://translator.bookfere.com/) 下载安装。
