### ISSUE TITLE
Calibre 3.21.0 无法让插件显示在主工具栏上进而导致无法使用

### ISSUE THREAD

**Issue by xflcx1991** [bookfere/Ebook-Translator-Calibre-Plugin#33]
Ubuntu18.04，无法安装Calibre最新版，用apt 安装就是3.21.0版本。这个版本安装看不到插件在主界面，根据readme介绍，需要手动添加，但是“工具栏和菜单”里面看不到本插件
![image](https://user-images.githubusercontent.com/3775351/236602227-b0891924-8fbe-410f-91bf-88e6edbbb983.png)
![image](https://user-images.githubusercontent.com/3775351/236602243-54525834-29e0-4a93-9cfb-7872590f7ee2.png)
插件是安装了的，也不允许个性化设置
![image](https://user-images.githubusercontent.com/3775351/236602267-e3d436f4-c061-45cf-a08a-e579d0490d09.png)

**Comment by bookfere** [comment]
右栏拉到底部也没有图标吗？

**Comment by xflcx1991** [comment]
> 右栏拉到底部也没有图标吗？

右栏？那就是主界面咯，没有
![image](https://user-images.githubusercontent.com/3775351/236603197-13d82f5a-9977-4202-9a83-e05eb1822773.png)

**Comment by xflcx1991** [comment]
命令行启动calibre有报错
![image](https://user-images.githubusercontent.com/3775351/236603254-b6e3420e-2c78-4f22-ade2-5a6f50c6c33b.png)

**Comment by xflcx1991** [comment]
删除插件再启动就没有报错，看来是插件和3.21.0版本的兼容问题？
![image](https://user-images.githubusercontent.com/3775351/236603290-966c9735-7c86-4ed6-b9b2-4876761f8d85.png)

**Comment by bookfere** [comment]
对，是插件和 Calibre 版本的兼容问题。我去下载一个相应的版本测试修复一下。

**Comment by bookfere** [comment]
问题已经修复了，你可以下载安装下面这个版本测试一下：

[ebook-translator_20230506141732.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11411617/ebook-translator_20230506141732.zip)

**Comment by xflcx1991** [comment]
> 

换了名字报错
![image](https://user-images.githubusercontent.com/3775351/236613076-940e3b99-58c9-4655-b70b-ec5384cb2d8d.png)

**Comment by bookfere** [comment]
再试试这个：[ebook-translator_20230506170750.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11411939/ebook-translator_20230506170750.zip)

**Comment by xflcx1991** [comment]
> 
安装后多了安放位置选择框，似乎好了。
![image](https://user-images.githubusercontent.com/3775351/236615523-9a4bc340-d000-48d6-8d02-239778326029.png)


但是功能测试不通过
![image](https://user-images.githubusercontent.com/3775351/236615660-ce603b39-2202-4a47-9328-bdb173e0e39c.png)

**Comment by bookfere** [comment]
这是用的哪一款翻译引擎？

**Comment by xflcx1991** [comment]
> 这是用的哪一款翻译引擎？

默认的google免费翻译，但是选择任何不要apikey翻译引擎都这样

**Comment by bookfere** [comment]
大概猜到问题所在了，试试这个版本：

[ebook-translator_20230506185116.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11412147/ebook-translator_20230506185116.zip)

这个 Calibre 版本依赖的包有点古旧，如果可能的话升级个版本是个更好的选择。

**Comment by xflcx1991** [comment]
> 大概猜到问题所在了，试试这个版本：
> 
> [ebook-translator_20230506185116.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11412147/ebook-translator_20230506185116.zip)
> 
> 这个 Calibre 版本依赖的包有点古旧，如果可能的话升级个版本是个更好的选择。

明白了，明天试试。不过calibre依赖glibc，这导致ubuntu18.04不能轻易升级到calibre到高版本。

**Comment by xflcx1991** [comment]
> 大概猜到问题所在了，试试这个版本：
> 
> [ebook-translator_20230506185116.zip](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/files/11412147/ebook-translator_20230506185116.zip)
> 
> 这个 Calibre 版本依赖的包有点古旧，如果可能的话升级个版本是个更好的选择。

好了，deepl free可以用
![图片](https://user-images.githubusercontent.com/3775351/236662282-f317b414-8f3a-48f4-a383-c0f14d561239.png)
