### ISSUE TITLE
[Bug report] I don't see Gemini Flash in engines

### ISSUE THREAD

**Issue by hoandesign** [bookfere/Ebook-Translator-Calibre-Plugin#341]
In google.py I saw the model Gemini Flash but after installing the plugin I didn't see that.

**Comment by bookfere** [comment]
I assume you installed the plugin from Calibre's plugin management. If you want to try the latest code, please follow the **[[Load from file] ](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/wiki/English#installation)** section of the installation instructions.
