### ISSUE TITLE
[功能请求] 建议增加豆包api的直接支持

### ISSUE THREAD

**Issue by rising337** [bookfere/Ebook-Translator-Calibre-Plugin#349]
很多工具对比了，发现豆包非常好用，翻译得很好，希望能直接支持。如果能调用起来，免费翻译更好。豆包本身还有exe。

**Comment by bookfere** [comment]
建议优先使用插件的自定义引擎功能调用对此翻译服务。在使用该功能过程中有任何疑问，欢迎随时提出。
