### ISSUE TITLE
当翻译因为某些原因中断后如何从中断处继续执行？

### ISSUE THREAD

**Issue by guanyubin** [bookfere/Ebook-Translator-Calibre-Plugin#35]
缓存没有起作用，翻译仍然是从头开始的

**Comment by bookfere** [comment]
是否同时满足这三个条件：同一输入路径、同一种目标语言、同一翻译引擎。

**Comment by guanyubin** [comment]
不好意思，是我疏忽了，第二次翻译时来源语言选了自动识别，与第一次指定为english不同，我猜是这个原因，改正后可以加载缓存。
