### ISSUE TITLE
[错误报告] 翻译失败

### ISSUE THREAD

**Issue by LSA16011** [bookfere/Ebook-Translator-Calibre-Plugin#356]
**基础信息**

* 操作系统: **macOS**
* Calibre 版本: **7.19.0**
* 插件版本：**v2.3.5**
* 插件来源: **安装自 Calibre**

**描述错误**
翻译失败

**期待变化**
前几次翻译都没问题，突然就无法翻译了。重装插件也没用

**屏幕截图**
添加合适的截图来帮助你解释问题
══════════════════════════════════════
行号：0
原文：Acknowledgments
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
状态：失败 1 次 / 等待 5 秒
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
错误信息：Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.lib.translation", line 136, in _translate_text
    translation = self.translator.translate(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.google", line 53, in translate
    return self.get_result(
           ^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
    raise Exception(
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
    br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;" onload="e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
<noscript>
<div style="font-size:13px;">
  In order to continue, please enable javascript on your web browser.
</div>
</noscript>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>var submitCallback = function(response) {document.getElementById('captcha-form').submit();};</script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="E-L1NTwfNsh9L91bbL7th5cfKRqFsQHc7h7IeRLRPIGKDJoVP--X5KOH_9UNBESANhb_xHnvxBybx00fPaf_HXD10WeNdjILWbVvreKEBgz72IZ67bqxYJ1i4yiUxtaNOpTZuzUeyvbuApHRQcDazOoVCEoUn6vZVPTOhvSocUdHYjX0MOuzBPG96KXo34EtmR_lqNLe51zGj8Q_LqqjT1HE7yo3PFU1pQXaNCWQ1fv-BEyxp5XUsSl_9NkheSWu3ICd72sLeOu0pF2crdrs8zLIkiY1u0c"></div>

<input type='hidden' name='q' value='EgQr57uiGNnywrgGIjA3IOISDKBZWkMU5gBMhsL6nw-dnNABYuBlY9V4zIbQ24YKZ57AxnWhywEWjWMhLpQyAXJaAUM'><input type="hidden" name="continue" value="https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>

Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>

<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

IP address: 43.231.187.162<br>Time: 2024-10-17T07:14:34Z<br>URL: https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments<br>
</div>
</div>
</body>
</html>
══════════════════════════════════════
行号：0
原文：Acknowledgments
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
状态：失败 2 次 / 等待 10 秒
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
错误信息：Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.lib.translation", line 136, in _translate_text
    translation = self.translator.translate(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.google", line 53, in translate
    return self.get_result(
           ^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
    raise Exception(
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
    br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;" onload="e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
<noscript>
<div style="font-size:13px;">
  In order to continue, please enable javascript on your web browser.
</div>
</noscript>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>var submitCallback = function(response) {document.getElementById('captcha-form').submit();};</script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="8uMOeKyOWOLyS7k1z2FC9cssigkzVCKtaOwIuwDAS8HrP8mcpZVaKyvmlLakInGXLRuvMAFzpZ_hvLhMzn_khhJmoOAw6DWYLCf8ps80Ba30ST0AF7xy7tkYT_8yHbMZ2Pnt7iX4YWNLTYrF86MuUxwWFEi0kx8ZDqd34DAwnUBo2yhPoVVaLTAx1hZ9P-_X25xq4Er77O8ffUjrNKUP6UCDzXBmHyXwIi2RgUQvMpYksQcHikmeAYrRE6tsEgRnHbwPzR-2HU9MteT9P-uop6boLzmbQuU"></div>

<input type='hidden' name='q' value='EgQr57uiGN_ywrgGIjDO5Oj4hgPubgg8XplXVHEr_7fNATeUr0A0dYv_N-wdcRUQQYXQkDxMIwlliEZWn8EyAXJaAUM'><input type="hidden" name="continue" value="https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>

Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>

<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

IP address: 43.231.187.162<br>Time: 2024-10-17T07:14:39Z<br>URL: https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments<br>
</div>
</div>
</body>
</html>
══════════════════════════════════════
行号：0
原文：Acknowledgments
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
状态：失败 3 次 / 等待 15 秒
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
错误信息：Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.lib.translation", line 136, in _translate_text
    translation = self.translator.translate(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.google", line 53, in translate
    return self.get_result(
           ^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
    raise Exception(
Exception: 无法解析返回的响应。原始数据：

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
    br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;" onload="e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
<noscript>
<div style="font-size:13px;">
  In order to continue, please enable javascript on your web browser.
</div>
</noscript>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>var submitCallback = function(response) {document.getElementById('captcha-form').submit();};</script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="0vPNrCvFNTGyp0ozfzU4BYRwS1W17lSKIrrFTUdjexafvrszAmdbA24D7-nEuSrqsbtgkb81Xt2I3piKp-UD4RxYVu4rK797CkMZd5Gji4n5AI0DUSrYAW5t9Tw9K0NcN1wGLBFa2LLj-wWI923PjFQLIgceK3CWmHtOcxxORUBR97MXMkxqh1VVcuy9vN1x3d0d_PqZRMKKeSIk1q-JnM1exBgCkeP3Bj4c4Yg8FoxQJFTaVWHgKgvmvHt6uUw5mxLGYC6XIRjJSVI1Ge_wAa8gOXuBa8U"></div>

<input type='hidden' name='q' value='EgQr57uiGOnywrgGIjCbxN-v526c-UT1r51-vrvnC-RSidAuQdNRDUgEkygKMmiZzkDG3QWBgQtr0sbi6PAyAXJaAUM'><input type="hidden" name="continue" value="https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>

Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>

<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

IP address: 43.231.187.162<br>Time: 2024-10-17T07:14:50Z<br>URL: https://translate.googleapis.com/translate_a/single?client=gtx&amp;sl=auto&amp;tl=zh-CN&amp;dt=t&amp;dj=1&amp;q=Acknowledgments<br>
</div>
</div>
</body>
</html>

**Comment by bookfere** [comment]
看起来是请求超过了 Google 翻译允许的频率，建议等一段时间，降低请求频率。如果使用了代理，可以更换线路再试试看。
