### ISSUE TITLE
能否开发成多线程模式，以提高翻译速度？

### ISSUE THREAD

**Issue by vssnipper** [bookfere/Ebook-Translator-Calibre-Plugin#36]
感谢作者的开发，非常好的工具。
但是能不能开发多线程，这个比谷歌官方文档翻译速度慢太多了，看任务显示详情似乎用的是单线程，能否开发成多线程模式？否则完全无法用作实际生产，因为速度甚至跟不上人工翻译。谢谢！

**Comment by bookfere** [comment]
谢谢建议。后面的版本会增加此功能。
