### ISSUE TITLE
[Feature request] Translates text containing variables, but keeps the variable name.

### ISSUE THREAD

**Issue by tuha1994** [bookfere/Ebook-Translator-Calibre-Plugin#369]
My idea is. Content describes the meaning of the code, and that content includes the variable of the described code. But add translated the variable name. So, keep the variable name inside the output content.

Original content: Because str(29) evaluates to '29', the expression 'I am ' + str(29) + ' years old.' evaluates to 'I am ' + '29' + ' years old.', which in turn evaluates to 'I am 29 years old.'. This is the value that is passed to the print() function.
If the result is great, the characters in the quotes are left unchanged.
Help me do that!

```html
<p xmlns="http://www.w3.org/1999/xhtml" class="indent"><span xmlns:epub="http://www.idpf.org/2007/ops" epub:type="pagebreak" id="page_16"></span>Because <span class="literal">str(29)</span> evaluates to <span class="literal">'29'</span>, the expression <span class="literal">'I am ' + str(29) + ' years old.'</span> evaluates to <span class="literal">'I am ' + '29' + ' years old.'</span>, which in turn evaluates to <span class="literal">'I am 29 years old.'</span>. This is the value that is passed to the <span class="literal">print()</span> function.</p>
```

**Comment by tuha1994** [comment]
Please help me.

**Comment by bookfere** [comment]
From the source code, you can see that these codes reside in elements that share the same class attribute:

```
<span class="literal">str(29)</span>
```

In the plugin’s settings, you can add this class name to the "**Reserve Element**" rules to prevent these elements from being translated.

However, please note that Calibre may change the class name during format conversion, and the plugin’s reserve element rules will match only the converted class name.

Therefore, I suggest converting the ebook first and inspecting the actual class name in which the code resides.

**Comment by tuha1994** [comment]
I tried to put span.literal In Reserve Element. As a result, the entire content containing span.literal was not translated.

**Comment by bookfere** [comment]
If elements with the `.literal` class contain not only code but other content as well, the situation may become complex. The plugin currently can only target elements by certain attributes, like class or ID, so you’ll first need to add a unique identifier to the elements that contain code.

**Comment by tuha1994** [comment]
Thanks you
