### ISSUE TITLE
Multiple api keys | Deepl

### ISSUE THREAD

**Issue by Dwtexe** [bookfere/Ebook-Translator-Calibre-Plugin#37]
I have multiple deepl free api keys and I would like to use them in a way that they are automatically activated as they run out of limits. can you make this enhancement? 

Thank you for your time.

**Comment by bookfere** [comment]
Thanks for your suggestion. We will work on it.

**Comment by Dwtexe** [comment]
It would be very nice if you can add the deepl handle_tag feature, otherwise markdowns are lost.

**Comment by bookfere** [comment]
Did you mean to preserve the original format while translating a Markdown document? Unfortunately, the plugin cannot perform this task because Calibre is unable to maintain the original formatting during the conversion process.

**Comment by Nil7x** [comment]
请问ChatGPT也还不支持多keys的配置吗？
