### ISSUE TITLE
[Bug report] Ignoring by Css Class not working

### ISSUE THREAD

**Issue by mrgchr** [bookfere/Ebook-Translator-Calibre-Plugin#370]
**Basic information**

* Operating System: **Windows**
* Calibre Version: **7.21**
* Plugin Version: **2.3.5** and  **ebook-translator_20241106161941**
* Plugin Installation: **Both From Calibre and Rolling Release**

**Describe the bug**
Ignore rule by css class ( e.g. `.notranslate`) seems not working.

Setting ignoring rules with attribute or css class name.
```
section[translate="no"]
.notranslate
```
![ignore_Settings](https://github.com/user-attachments/assets/0b26c2d1-0cce-4d0e-8004-2c0d3efe969e)

Add css class which to be ignored.

![ignore_byCssClass_1](https://github.com/user-attachments/assets/e55015b6-267d-4149-9f16-f155ff455966)

But elements with above ignoring class are not ignored.

![ignore_byCssClass_2](https://github.com/user-attachments/assets/06c9b906-3dfe-4efd-a6f6-2ed5f9807c82)

Ignoring by attribute is working.

![ignore_byAttribute_1](https://github.com/user-attachments/assets/f2ca2506-472b-4c3f-a392-76f0c4a7d860)
![ignore_byAttribute_2](https://github.com/user-attachments/assets/8008fe82-3838-4a02-808c-9a44ecfd789a)

**Comment by mrgchr** [comment]
@tuha1994 thanks for reply.

> You're doing it wrong, 

Not sure where my mistake is. And why `p.program` works to `class="programs"`?
Re-Try with ignoring rule `section.notranslate` does not work.

**Comment by tuha1994** [comment]
Please send full Element

**Comment by mrgchr** [comment]
@tuha1994 
What do you mean full Element?

The epub file I used in this Issue is following **Accessible EPUB 3**. (EPUB/pr01.xhtml)
<http://idpf.github.io/epub3-samples/30/samples.html>

And I think I have already described steps how to reproduce.

**Comment by bookfere** [comment]
@mrgchr

Here is the answer to a similar question; I hope this helps.

> You may have used the CSS selectors based on the source code of the original EPUB file. However, Calibre changes these selectors during conversion, which affects how the plugin operates. Therefore, your plugin's filter rules can only apply to the modified selectors. I suggest you first convert the EPUB file (or double-click the item in the plugin's original list to check its source code) and then verify the CSS selectors to use.
> 
> For example, in your case, one of the code blocks in the original EPUB file is:
> 
> `<p class="source-code">$ git add hello.txt</p>`
> 
> But after Calibre's format conversion, it became:
> 
> `<p class="source-code1">$ git add hello.txt</p>`
> 
> Notice that a "1" has been added to the class attribute. So, you need to set the rule as ".source-code1" instead of ".source-code" to target the code block.

**Comment by mrgchr** [comment]
@bookfere 
Thanks for reply.

I have confirmed there  are significant changes in new epub when converting epub to epub in calibre.
That makes sense above behavior.

However, re-converting epub to epub by myself is little bit weird to me.
So I would use custom attribute (like `trasnlate="no"` and `[translate="no"]`, same as  DeepL).

Thanks for your help.
