### ISSUE TITLE
有没有任务暂定与恢复功能？

### ISSUE THREAD

**Issue by guanyubin** [bookfere/Ebook-Translator-Calibre-Plugin#39]
翻译一本书的时间通常很长，任务如何暂停和恢复？calibre本身限制没法继续？翻译过程中windows更新了重启了…

**Comment by bookfere** [comment]
在插件设置中开启缓存后可以随时中断翻译，下次翻译同一本书时，只要同时满足同一翻译引擎、同一输入路径、同一来源语言、同一目标语言这四个条件，就会自动读取缓存而不会重新翻译。
