### ISSUE TITLE
请求添加epub文本翻译后的ai润色功能和给chat gpt自定义设置prompt以提高翻译成品的质量，与适配开发sigil版的插件

### ISSUE THREAD

**Issue by MZHMXH** [bookfere/Ebook-Translator-Calibre-Plugin#4]
请求添加epub文本翻译后的ai润色功能和给chat gpt自定义设置prompt以提高翻译成品的质量，与适配开发sigil版的插件。翻译后的润色功能在文本翻译出的成品和阅读质量上会有很大的提升。此外还可以添加选择需要翻译文本的翻译范围。望开发者可以考虑一下我的建议。同时也祝开发者项目顺利开发，一帆风顺！可以帮助到更多需要的朋友@bookfere

**Comment by MZHMXH** [comment]
希望开发者可以添加一个由用户自行选择是否翻译后只保留翻译结果不保留翻译前的原文的选项功能！

**Comment by bookfere** [comment]
谢谢建议。自定义 ChatGPT 提示词、过滤待翻译内容和只保留翻译结果的功能会添加到之后版本的偏好设置中。Sigil 版本插件限于个人精力目前还没有计划。

另外，你提到的“AI润色功能”是指将翻译结果重新发给 ChatGPT 进行润色吗？

**Comment by MZHMXH** [comment]
> 中

是的，我提到的“AI润色功能”是指将翻译结果重新发给ChatGPT 进行润色，也可以选择多次重复润色以达到翻译成品的阅读体验得到提升

**Comment by MZHMXH** [comment]
了解，辛苦了开发者！

**Comment by MZHMXH** [comment]
> 了解。不过类似的复审功能不适合放在翻译过程中。插件现在只是简单把翻译过程写到了日志中，之后会增加一个专门的监控面板替代这种方式，这样就比较方便复审翻译结果以及改善不满意的地方。

再建议给chat gpt添加屏蔽审查的脚本或者内置绕开审查的代码供用户选择！
