### ISSUE TITLE
Enhance cache to store pre-translated text, not just md5

### ISSUE THREAD

**Issue by jtippett** [bookfere/Ebook-Translator-Calibre-Plugin#42]
The current cache structure stores only the md5 of the pre-translated content and the response from the translator. This makes it difficult to identify mis-translations and manually correct them. It also lacks a column indicating the target language, making it inflexible for multi-language projects.

I do not believe the space saving of storing md5 only warrants the loss of functionality from not also storing the plaintext. We are generally talking about a few megabytes, at most. Would it be possible to extend the cache to also store the pre-translated text? Also, it might be useful to make it more obvious where it's stored (was rather hard to find on osx)

**Comment by bookfere** [comment]
Thank you for your suggestion. I will enhance the cache feature to include more information and make it easier to find.

**Comment by jtippett** [comment]
Thank you very much. I believe this will be very helpful for users, as often the LLM (I use ChatGPT) will randomly give some very irrelevant answer, or explain that it is an AI, or say it needs more context, or whatever. This enhancement will make it simpler for users to locate such occurences and either manually correct them or simply delete them and try again.

Thanks again for such a great tool.
