### ISSUE TITLE
翻译时，批量设置输出格式，来源语言

### ISSUE THREAD

**Issue by QingHui653** [bookfere/Ebook-Translator-Calibre-Plugin#44]
翻译时，批量设置输出格式，来源语言。
如题，有很多本需要翻译，但是我又想保存为txt, 这样导致每一本都需要手动修改。

**Comment by bookfere** [comment]
“输出格式”可以像“目标语言”一样，在设置中添加一个偏好格式。不过，“来源语言”在什么情况下需要批量设置呢？

**Comment by QingHui653** [comment]
来源语言不太需要设置,选择自动即可. 不过我通常是特地选择的
