### ISSUE TITLE
Fix empty content 修复分割空白内容导致停止

### ISSUE THREAD

**Issue by baowonton** [bookfere/Ebook-Translator-Calibre-Plugin#45]
首先，十分感谢作者的工作。由于我在使用的过程发现一个问题。
在翻译一本书的时候会出现分割空白的情况导致停止。(Patrick Henry Winston - Make It Clear_ Speak and Write to Persuade and Inform-MIT Press (2020) )，可以参考我的代码[修复分割空白](https://github.com/baowonton/Ebook-Translator-Calibre-Plugin/tree/FixEmptyContent)，当时是简单跟着报错修复的，作者应该会有更好的方法。

**Comment by baowonton** [comment]
在翻译一本书的时候会出现分割空白的情况导致停止。(Patrick Henry Winston - Make It Clear_ Speak and Write to Persuade and Inform-MIT Press (2020) )，可以参考我的代码[修复分割空白](https://github.com/baowonton/Ebook-Translator-Calibre-Plugin/tree/FixEmptyContent)

**Comment by bookfere** [comment]
谢谢反馈！从你提供的代码看，好像是在处理“原文”或“译文”为空的情况。

插件在抽取内容时已经在尝试排除所有内容为空的“原文”，如果仍出现这种错误，就表示抽取元素那一块存在问题，需要修复。获取译文时倒是没有判断是否为空，按理说，只要向翻译引擎发送了原文，除非获取不到响应，否则不应该出现响应空的情况，不过也不排除会出现这种情况。

这两个问题都有待验证。是否方便提供一下出现此问题的电子书文件（或相关页面）？

**Comment by bookfere** [comment]
谢谢提供测试文件。这是插件自身的错误，已在新版本中修复。新版本代码提交后会自动关闭此 Issue，请届时下载试用。

**Comment by bookfere** [comment]
谢谢提供测试文件。这是插件自身的错误，已在新版本中修复。新版本代码提交后会自动关闭此 Issue，请届时下载试用。
