### ISSUE TITLE
是否考慮支持Azure Openai的Chatgpt

### ISSUE THREAD

**Issue by ickacn** [bookfere/Ebook-Translator-Calibre-Plugin#49]
如題，azure openai也針對很多人開放了，和openai官方的都一樣的模型，只是用的方式不大一樣。

**Comment by bookfere** [comment]
从 Azure OpenAI Service 提供的[文档](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#chat-completions)看和 OpenAI 提供的 API 是兼容的。 新版本参考文档加上了 Azure ChatGPT，但是我这里没条件测试，新版发布后你可以试一试，有问题再反馈。这个 Issue 会在新版代码提交后自动关闭。

**Comment by ickacn** [comment]
可以使用，剛剛測試是沒有報錯。謝謝
