### ISSUE TITLE
添加对腾讯翻译API的支持（腾讯翻译API的一些有用特性无法通过自定义翻译引擎支持）

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#53]
腾讯翻译API提供了[文本翻译](https://cloud.tencent.com/document/api/551/15619)和[批量文本翻译](https://cloud.tencent.com/document/api/551/40566)两个API，以下是我阅读API文档时发现的这两个API各自的一些特性以及一些想法：

1. 文本翻译API：可选的```UntranslatedText```参数，用来标记不希望被翻译的文本内容，这个参数可以考虑和词汇表功能结合使用，减少对原文内容的处理，进而减少因此造成的对翻译结果的影响，毕竟API文档里也说了非常规翻译文本可能会翻译失败。缺点时每次请求只支持配置一个不被翻译的单词，如果一段中出现多个需要处理的单词，可以考虑根据词汇表中的顺序优先处理顺序靠前的单词。

2. 批量文本翻译API：请求中的```SourceTextList```字段是一个字符串数组，响应中的```TargetTextList```字段也是一个数组。该API应用在在处理合并翻译的场景时无需再添加标记，进而减少额度的使用，也不用担心标记影响翻译，缺点是不支持```UntranslatedText```参数。

这两个API不同场景下各有优劣，可以考虑分别实现。

**Comment by bookfere** [comment]
没有太大的兴趣添加腾讯的产品。
