### ISSUE TITLE
[功能请求]高级模式页面添加一键选择未翻译段落选项

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#57]
翻译到一半停止翻译调整了一下设置，再翻译时不想再翻一遍已经翻译了部分，而未翻译部分散成了并发数块，如果并发数设置的比较高，手动选择就很不方便。

**Comment by bookfere** [comment]
这个功能是已存在的，点击【翻译全部】按钮后，会忽略已翻译过的内容。

**Comment by WeeAris** [comment]
> 这个功能是已存在的，点击【翻译全部】按钮后，会忽略已翻译过的内容。

Thanks
