### ISSUE TITLE
可以搭配DeepLX项目弄个本地的API

### ISSUE THREAD

**Issue by uzcool** [bookfere/Ebook-Translator-Calibre-Plugin#6]
项目地址
https://github.com/OwO-Network/DeepLX

```
import httpx, json

deeplx_api = "http://127.0.0.1:1188/translate"

data = {
	"text": "Hello World",
	"source_lang": "EN",
	"target_lang": "ZH"
}

post_data = json.dumps(data)
r = httpx.post(url = deeplx_api, data = post_data).text
print(r)


```

**Comment by bookfere** [comment]
之后的版本可以添加自定义翻译引擎功能来满足这个需求。

**Comment by killo3967** [comment]
Yo estaria agradecido que incorporara esta funcionalidad. La creo muy interesanta.

**Comment by dyoghenes** [comment]
Hi! Sorry for reopening this. What code should I use to get this working?

`{
    "name": "DeepL X",
    "languages": {
        "source": {
            "Source Language": "DE"
        },
        "target": {
            "Target Language": "EN-GB"
        }
    },
    "request": {
        "url": "http://127.0.0.1:1188/translate",
        "method": "POST",
        "data": {
            "source_lang": "<source>",
            "target_lang": "<target>",
            "text": "<text>"
        }
    },
    "response": "response"
}`

Using this code returns to me HTTP Error 400: Bad Request in Calibre, and a 404 error in the DeepLX

**Comment by shantaram108** [comment]
> @dyoghenes I see that you received a 400 response status code, indicating that the translation engine API rejected your request. This could be due to the instability of the API you used.

I used the same settings and get the following error:


```
 Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 201, in get_result
  File "calibre_plugins.ebook_translator.engines.custom", line 134, in _parse
Exception: Response was parsed incorrectly.

{"code":200,"data":"Hallo Welt!"}
```

**Comment by bookfere** [comment]
It is a parse error, please try to revise the response part like this `"response": "response['data']"`.

**Comment by shantaram108** [comment]
it works, thank you!

**Comment by shantaram108** [comment]
I have another issue now:

I started my own DeeplX service and tested it in my browser with "http request maker" addon for firefox. It works just fine. When I replace https://deeplx.vercel.app/translate with http://127.0.0.1:1188/translate in the custom config it to have it like this:

```
{`
    "name": "DeepL X",
    "languages": {
        "source": {
            "Source Language": "EN"
        },
        "target": {
            "Target Language": "DE"
        }
    },
    "request": {
        "url": "http://127.0.0.1:1188/translate",
        "method": "POST",
        "data": {
            "source_lang": "<source>",
            "target_lang": "<target>",
            "text": "<text>"
        }
    },
    "response": "response['data']"
}
```

I get the following error
```

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 67, in translate_text
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
Exception: Can not parse returned response. Raw data: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 400: Bad Request

{"code":404,"message":"No text to translate"}
```

In the HTTP Request Maker addon for Firefox, just change the URL address and it works for both URL, the one from vercel.app and my localhost. So I guess it should be the same when changing the url in the custom config. Can you help me figuring out why it wont send the text to the POST request?

**Comment by bookfere** [comment]
Maybe you need to add an appropriate request header:

```
"headers": {
    "Content-Type": "application/json"
}
```

By the way, the free version of DeepL has already been added to the built-in engine of the plugin, so it is not necessary to use a custom engine.

**Comment by micropythondevel** [comment]
hello 
tatus: Failed 1 times / Sleeping for 5 seconds
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
Error: Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.lib.translation", line 136, in _translate_text
    translation = self.translator.translate(text)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
    return self.get_result(
           ^^^^^^^^^^^^^^^^
  File "calibre_plugins.ebook_translator.engines.base", line 210, in get_result
    raise Exception(
Exception: No se pudo analizar la respuesta devuelta. Datos sin procesar: 

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 197, in get_result
    br.open(request)
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 400: BAD REQUEST

{"error":"Invalid request: missing q parameter"}


my config 

{
    "name": "freetranslate",
    "languages": {
        "source": { "Source Language": "auto" },
        "target": { "Target Language": "es" }
    },
    "request": {
        "url": "http://127.0.0.1:5000/translate",
        "method": "POST",
        "headers": {
        "Content-Type": "application/json"
         },
        "data": {
            "source": "<source>",
            "target": "<target>",
            "text": "<text>",
             "api_key": ""

        }
    },
    "response": "response['data']"
}
I don't know where the error could be, can someone help me? I use a local version of LibreTranslate

Thanks

我不知道错误可能出在哪里，有人可以帮助我吗，我使用本地版本的 libretranslate

谢谢
