### ISSUE TITLE
能否提供重新修改已导出epub文件译文的功能

### ISSUE THREAD

**Issue by egaojing** [bookfere/Ebook-Translator-Calibre-Plugin#66]
在导出翻译的epub文件之前，都可以修改译文；在导出epub书籍后，现在只能通过sigil这样的软件修改；能否提供再次修改已导出epub书籍的功能，阅读过程中发现翻译不满意的地方，通过插件回到可以修改各个翻译的部分，重新修改部分译文

**Comment by bookfere** [comment]
关于此问题的讨论见 #64
