### ISSUE TITLE
输出路径问题：如果书籍名称包含特殊字符，如英文冒号“：”，则会保存失败

### ISSUE THREAD

**Issue by michaelpopes** [bookfere/Ebook-Translator-Calibre-Plugin#68]
首先，非常感谢这个插件！非常非常有用，打开了一个新的世界！谢谢！

有个小问题，报错信息如下：
EPUB output written to C:\Users\...\Documents\Docs\Calibre...\The ... of Money: ... (Chinese (simplified)).epub

可能保存时将特殊字符替换成空格即可。

再次感谢！

**Comment by michaelpopes** [comment]
另外，请问一个问题哈：如果同时启动多个任务，是否因为并发的增多，导致DeepL Free更容易返回429？

**Comment by bookfere** [comment]
谢谢反馈。关于文件名的问题会在下个版本修复。关于 429 错误，我们的建议是，对于免费的翻译引擎，除了 Google（Free）外不要用并发请求，并且，一旦出现请求错误，要适当加大请求间隔。
