### ISSUE TITLE
Footnote 問題

### ISSUE THREAD

**Issue by Jackie00765** [bookfere/Ebook-Translator-Calibre-Plugin#71]
有時遇上footnote時，翻譯會中斷，要再按翻譯才能繼續，而且翻譯的文字每與原文次序不同。

例如：

原文：

Aaaaaaaa Bbbbbbbb[1] Ccccccc

翻譯：
Bbbbbbb Ccccccc Aaaaaaaa

**Comment by bookfere** [comment]
能否提供一下原文的 HTML 代码。在高级模式下，双击某个段落会在右侧区域显示 HTML 代码。
