### ISSUE TITLE
字符数统计的疑问

### ISSUE THREAD

**Issue by Benjamin-Watson0** [bookfere/Ebook-Translator-Calibre-Plugin#72]
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/112467275/e7da1b68-25bf-4ec0-a758-f535bf17919e)
这是count page统计的结果，显示189391个字符
这本书使用百度翻译显示消耗量10080086个字符，还没成功，因为我余额没了😭（每月最多100万，百度翻译忘记充值了）
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/112467275/2c8de505-6d24-4b96-96ea-b1ddef5128a3)
这是咋花的啊。

当时看了错误报告，显示就是
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/112467275/e6be254d-37df-473f-8c74-fb51ff93af30)

**Comment by bookfere** [comment]
你可以把电子书发送到书伴邮箱，我们可以帮你统计一下发送给翻译引擎的总字符数供你对比。另外，我们还需要知道你是否开启了合并翻译，如果开启了合并的字符数是多少。

**Comment by bookfere** [comment]
对于这本书，插件向翻译引擎发送的的总字符数为：**1017426**。

后面的版本会为插件添加字符统计功能，到时你可以查看此数据。

**Comment by bookfere** [comment]
只要开启了缓存功能，并且确保所翻译电子书的这四个因素相同：**输入路径**、**翻译引擎名称**、**目标语言**以及**合并翻译字符数**（未开启合并翻译状态下为 0），就不会重复翻译已经翻译过的内容。

另外，除上面提到的那四个因素外，还有两个潜在的因素：对插件的内容抽取和缓存功能的更改，这可能会导致旧版本缓存失效。不过，除非有充分的理由作改动，插件会尽可能兼容旧版本。
