### ISSUE TITLE
Gnome桌面环境下，高级模式翻译正在进行时无法切换到桌面的其他工作区

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#74]
大多数Linux桌面环境都有工作区这个功能，这有助于同时让多个程序窗口在前台运行但又不至于全部挤在一块，我的gnome桌面环境当然也有。
我发现插件在高级模式下，正在进行翻译时我无法切换到其他工作区。
我的操作系统时Nobara 37 Gnome version，Gnome版本是43.2，wayland环境

**Comment by bookfere** [comment]
手头没有这个系统环境，不好测试这个问题。

**Comment by anartigone** [comment]
操作系统：kali-linux-2023.2
内核版本：Linux 6.1.0-kali9-amd64
Gnome版本：44.1
桌面环境：x11+gdm3
主程序版本：Calibre 6.23
插件版本：v2.1.1

测试方法：在高级模式下运行翻译时，使用Spuer+Page Up/Down切换工作区，使用Shift+Super+Page Up/Down在工作区之间移动窗口。
测试结果：一切正常，无法复现问题。

由于是在虚拟机环境所以无法启用wayland，建议你自己切换到x11环境测试。

**Comment by WeeAris** [comment]
> 操作系统：kali-linux-2023.2 内核版本：Linux 6.1.0-kali9-amd64 Gnome版本：44.1 桌面环境：x11+gdm3 主程序版本：Calibre 6.23 插件版本：v2.1.1
> 
> 测试方法：在高级模式下运行翻译时，使用Spuer+Page Up/Down切换工作区，使用Shift+Super+Page Up/Down在工作区之间移动窗口。 测试结果：一切正常，无法复现问题。
> 
> 由于是在虚拟机环境所以无法启用wayland，建议你自己切换到x11环境测试。

在openSUSE Tumbleweed Gnome 44.3上测试也没有复现成功，推测可能是与Nobara Linux中的某个GNOME Shell extension发生了冲突，该问题可能不具有普遍性。
