### ISSUE TITLE
[Bug] 正在翻译时电脑突然断电关机，重启后翻译进度全部丢失

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#75]
高级模式下进行翻译，正在翻译时电脑突然断电关机，重启后当前书籍翻译进度全部丢失，希望对缓存和翻译进度定时备份，另外希望加入自定义缓存路径的设置，因为flatpak版的Calibre，点打开缓存目录是没有反应的，估计是因为在沙箱里，没有权限

**Comment by bookfere** [comment]
缓存的丢失可能是和操作系统对临时文件的处理有关，自定义缓存路径应该能避免这个问题。

**Comment by WeeAris** [comment]
> 缓存的丢失可能是和操作系统对临时文件的处理有关，自定义缓存路径应该能避免这个问题。

刚发现不需要突然断电，只要重启就会丢失

**Comment by bookfere** [comment]
有的操作系统会在重启时清空临时文件，有的会定期清理。你可以确认一下你所用操作系统是如何处理临时文件的。对插件来说，缓存算是一个比较重要的功能，毕竟很多用户是通过付费翻译引擎得到的翻译数据，不应该使用临时文件，后面的版本会用更可靠的方式来存放缓存，比如自定义路径、云端同步等。
