### ISSUE TITLE
[Feature Request] 增加选项，请求失败超过最大次数时，不停止翻译

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#76]
自己写API把Poe bot封装成了翻译引擎，尽管通过调教prompt实现99%以上的稳定性，但仍有不到1%的请求会出问题，而且出问题的请求大概率能成功复现，我推测是这部分请求触及到模型本身的一些缺陷，需要人工介入处理。
但是这处理起来比较麻烦，所以我希望增加一个选项：当请求超过最大次数时，跳到下一段继续翻译，直到所有翻译完成后再弹出一个窗口告诉我哪些地方翻译失败了，或者在“状态”这一栏红字标注。这样我就不用盯着它干活了（毕竟poe有速率限制，不能翻太快）。

**Comment by bookfere** [comment]
目前正在改进的版本正好实现了这个特性，翻译过程中会忽略失败的条目，完成后提供失败条目的提示。

**Comment by bookfere** [comment]
版本 v2.1.0 已实现此功能，需要在设置中将“**最大错误次数**”设置为 **0**。
