### ISSUE TITLE
增加选项，请求失败超过最大次数时，停止翻译（对，请停止翻译，而不是继续翻译剩余段落）

### ISSUE THREAD

**Issue by michaelpopes** [bookfere/Ebook-Translator-Calibre-Plugin#77]
再次感谢开发了这么好用的插件！

最近升级之后，发现使用DeepL Free的时候，一旦失败，则后续所有的翻译请求都一定会失败，因此没有必要再继续翻译剩余的部分，反而“停止翻译”是最优的选择。之后，只需要人工重新启动这个翻译任务，则剩下的翻译请求又会成功。

当然，如果可以实现“DeepL Free 尽管前面段落的失败，后续段落仍然可以继续翻译成功”，则“不停止翻译”才是最优选择。

非常感谢！

**Comment by bookfere** [comment]
失败后出现的提示是“Too Many Requests”吗？有没有尝试加大请求间隔或重试次数？

**Comment by WeeAris** [comment]
> 再次感谢开发了这么好用的插件！
> 
> 最近升级之后，发现使用DeepL Free的时候，一旦失败，则后续所有的翻译请求都一定会失败，因此没有必要再继续翻译剩余的部分，反而“停止翻译”是最优的选择。之后，只需要人工重新启动这个翻译任务，则剩下的翻译请求又会成功。
> 
> 当然，如果可以实现“DeepL Free 尽管前面段落的失败，后续段落仍然可以继续翻译成功”，则“不停止翻译”才是最优选择。
> 
> 非常感谢！
我怀疑你那不是请求失败了，所以才没停

**Comment by michaelpopes** [comment]
没有提示“Too Many Requests”。提示如下（注：除了第一条，后续大概有几百条全部是同样的错误）：
------------------------------
原文：Patches notwithstanding, a lot of the passengers get seasick anyway, these first two howling days. It turns out that a seasick person really does look green, though it’s an odd, ghostly green, pasty and toadish, and more than a little corpselike when the seasick person is dressed in formal dinnerwear.
译文：尽管有补丁，很多乘客还是会晕船，在这头两天的嚎叫中。事实证明，晕船的人看起来确实是绿色的，尽管那是一种奇怪的、幽灵般的绿色，糊状和蛤蟆状，而且当晕船的人穿着正式的晚宴服装时，还有点像尸体。
------------------------------
原文：For the first two nights, who’s feeling seasick and who’s not and who’s not now but was a little while ago or isn’t feeling it yet but thinks it’s maybe coming on, etc., is a big topic of conversation at good old Table 64 in the Five-Star Caravelle Restaurant. Common suffering and fear of suffering turn out to be a terrific icebreaker, and ice-breaking is important, because on a 7NC you eat at the same designated table with the same companions all seven nights. Discussing nausea and vomiting while eating intricately prepared and heavy gourmet foods doesn’t seem to bother anybody.
无法从翻译引擎API获取数据。
5 秒后重试。
[2023-06-26 23:11:50] 正在重试 1 ...（60秒后超时）
无法从翻译引擎API获取数据。
10 秒后重试。
[2023-06-26 23:11:01] 正在重试 2 ...（60秒后超时）
无法从翻译引擎API获取数据。
------------------------------
原文：Even in heavy seas, 7NC Megaships don’t yaw or throw you around or send bowls of soup sliding across tables. Only a certain subtle unreality to your footing lets you know you’re not on land. At sea, a room’s floor feels somehow 3-D, and your footing demands a slight attention good old planar static land never needs. You don’t ever quite hear the ship’s big engines, but when your feet are planted you can feel them, a kind of spinal throb—it’s oddly soothing.
无法从翻译引擎API获取数据。
5 秒后重试。
[2023-06-26 23:11:06] 正在重试 1 ...（60秒后超时）
无法从翻译引擎API获取数据。
10 秒后重试。
[2023-06-26 23:11:17] 正在重试 2 ...（60秒后超时）
无法从翻译引擎API获取数据。
------------------------------
原文：Walking is a little dreamy also. There are constant slight shifts in torque from the waves’ action. When heavy waves come straight at a Megaship’s snout, the ship goes up and down along its long axis—this is called pitching. It produces a disorienting deal where you feel like you’re walking on a very slight downhill grade and then level and then on a very slight uphill grade. Some evolutionary retrograde reptile-brain part of the CNS is apparently reawakened, though, and manages all this so automatically that it requires a good deal of attention to notice anything more than that walking feels a little dreamy.
无法从翻译引擎API获取数据。
5 秒后重试。
[2023-06-26 23:11:23] 正在重试 1 ...（60秒后超时）
无法从翻译引擎API获取数据。
10 秒后重试。
[2023-06-26 23:11:33] 正在重试 2 ...（60秒后超时）
无法从翻译引擎API获取数据。
------------------------------
原文：Rolling, on the other hand, is when waves hit the ship from the side and make it go up and down along its crosswise axis. When the m.v. Nadir rolls, what you feel is a very slight increase in the demands placed on the muscles of your left leg, then a strange absence of all demand, then demands on the right leg. The demands shift at the rate of a very long thing swinging, and again the action is usually so subtle that it’s almost a meditative exercise to stay conscious of what’s going on.
无法从翻译引擎API获取数据。
5 秒后重试。
[2023-06-26 23:11:39] 正在重试 1 ...（60秒后超时）
无法从翻译引擎API获取数据。
10 秒后重试。
[2023-06-26 23:11:49] 正在重试 2 ...（60秒后超时）
无法从翻译引擎API获取数据。
------------------------------

**Comment by michaelpopes** [comment]
有没有尝试加大请求间隔或重试次数？

目前的参数设置如下：
并发限制：1
时间间隔：15
重试次数：2
超时：60

此前跑的都还挺好，一本书也就一到两次报错。重启后就好了。

**Comment by michaelpopes** [comment]
原因好像找到了，之前的参数是：
并发限制：0  <-
时间间隔：15
重试次数：2
超时：60

这种情况不会停止翻译，但后续所有的翻译都是“无法从翻译引擎API获取数据。”

修改并发限制为1，只会尝试一次失败，然后就停止翻译了。
并发限制：1  <-
