### ISSUE TITLE
[Bug]自定义引擎名称中如果有小数点，部分引擎设置会失效

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#78]
已确认受影响的设置有：并发限制、时间间隔、超时时长

**Comment by bookfere** [comment]
去掉小数点就会恢复正常吗？名称应该和这些数值没关联的，不过也有可能是设置自身的问题。新版本对这些都做了一些更改，到时可以测试一下问题还是否存在。

**Comment by WeeAris** [comment]
> 去掉小数点就会恢复正常吗？名称应该和这些数值没关联的，不过也有可能是设置自身的问题。新版本对这些都做了一些更改，到时可以测试一下问题还是否存在。

是的，去掉之后就恢复正常了

**Comment by bookfere** [comment]
可以测试一下 v2.1.0 看是否还存在此问题。

**Comment by WeeAris** [comment]
> 可以测试一下 v2.1.0 看是否还存在此问题。

测试了v2.1.1，依然存在这个问题
