### ISSUE TITLE
View deepl free remains quote.

### ISSUE THREAD

**Issue by killo3967** [bookfere/Ebook-Translator-Calibre-Plugin#8]
Hi
Could be posible to connect to deepl and view who many characters have i remain in my quote and compare with the book to know i i have enought to translate the book?

"Deepl api free" has only 500.000 characters in quote and could be very usefull to know this data prior to translate and anticipate the posible fail.

**Comment by bookfere** [comment]
This feature will be added in the next version, please stay tuned.
