### ISSUE TITLE
[Feature Request] 增加选项，高级模式下允许从已导出的epub中加载翻译结果

### ISSUE THREAD

**Issue by WeeAris** [bookfere/Ebook-Translator-Calibre-Plugin#81]
作为一种缓存已经丢失的情况下的补救措施吧，也可以结合重新设定合并翻译字数，用来修复个别段落GPT老翻不对的问题。为了避免遇到太多意料外的情况，可以进行进行较严格的格式检查，并利用该检查反过来评估译文中标记是否正确保留/处理。

**Comment by bookfere** [comment]
从已导出的电子书中还原译文不太可行，感觉还是确保缓存不丢失是更好的办法。

**Comment by WeeAris** [comment]
> 从已导出的电子书中还原译文不太可行，感觉还是确保缓存不丢失是更好的办法。

双语的话应该可以吧，可以比对原文部分

**Comment by bookfere** [comment]
这个需求和 #64 类似。我还是感觉这样操作不太合理。假设有 A、B、C、D 四个用户，A 开启了合并段落，B 删除了某些段落，C 忽略了某些段落，D 选择不保留译文，这几种情况下，想要从输出的电子书中还原译文，还让他们和原来的段落相对应，即便实现也比较复杂。关键是，这个问题的症结是缓存的意外丢失，如果能够指定缓存位置确保它不被意外删除，问题就不存在了。
