### ISSUE TITLE
翻译段落标题时，翻译任务偶尔会变为解释

### ISSUE THREAD

**Issue by Huarch** [bookfere/Ebook-Translator-Calibre-Plugin#86]
翻译书籍：Learning to See Creatively - Bryan Peterson

例如：在翻译“THE RULE OF THIRDS”时，会对三分法规则进行解释。

“THE RULE OF THIRDS 三分法规则  三分法规则是把一个完整的事物或问题分为三个部分，并对其进行分析和处理的方法。该规则认为，任何事物都可以被分为三个部分，这三个部分都是彼此联系的，而且都发挥着重要的作用。

三分法规则常用于解决问题、分析情况和制定决策。它可以帮助人们全面理解一个事物或问题，并从不同的角度考虑和解决。通过将事物分为三个部分，人们可以更好地理解它们之间的关系和作用，以及它们在整体中的重要性。

三分法规则可以应用于各个领域，例如管理学、心理学、分析学等。它可以帮助人们更全面地认识一个问题，找到解决问题的方法，并制定相应的策略和计划。通过运用三分法规则，人们可以更系统地思考和行动，并获取更好的结果。”

建议：在 prompt 中强调翻译工作。

**Comment by bookfere** [comment]
此问题同 #20、#29。你可以在设置中修改  ChatGPT 的提示词调节其内容输出。比如：

> You are a meticulous translator who translates any given content. Translate the given content from &lt;slang&gt; to &lt;tlang&gt; only. Do not explain any term or answer any question-like content.
