### ISSUE TITLE
第三方的GPT api报307错误

### ISSUE THREAD

**Issue by riverai** [bookfere/Ebook-Translator-Calibre-Plugin#89]
我用的是这里的模型：
https://[chimeragpt.adventblocks.cc/v1/models](https://chimeragpt.adventblocks.cc/v1/models)

后端地址是：https://chimeragpt.adventblocks.cc/v1/chat/completions/
选的是gpt4或者3.5 turbo模型。
填写了discord获得的密钥。
在翻译之前，我用其他客户端测试过，密钥，网址（https://chimeragpt.adventblocks.cc/v1）都是通的，能聊天。但是填写到这里尝试翻译，就每次都报错，完全无法翻译。
不知道原因是什么？

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 307: Temporary Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 89, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 181, in get_result
Exception: 无法解析返回的响应。原始数据：
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 307: Temporary Redirect

**Comment by anartigone** [comment]
参考[这里](https://github.com/nomic-ai/gpt4all/issues/1202#issue-1804862178)，可能是单次token量超载或者触发限制了吧，你可以在能聊天的客户端手动测试一下相同文本。第三方api可以做很多限制和调整，我觉得这个问题是服务端造成的，应该找上游。

**Comment by riverai** [comment]
> 参考[这里](https://github.com/nomic-ai/gpt4all/issues/1202#issue-1804862178)，可能是单次token量超载或者触发限制了吧，你可以在能聊天的客户端手动测试一下相同文本。第三方api可以做很多限制和调整，我觉得这个问题是服务端造成的，应该找上游。

不是，和你说的这个没什么关系，因为我这个也是在线模型，完全兼容GPT API，并不是本地模型啊。
而且我在插件的GPT配置里面点了“测试”，就一句话“hello world"也不行，也不是token超过限制。
同期用相同的密钥和API已经测试过可以使用GPT4 对话聊天。

**Comment by anartigone** [comment]
> > 参考[这里](https://github.com/nomic-ai/gpt4all/issues/1202#issue-1804862178)，可能是单次token量超载或者触发限制了吧，你可以在能聊天的客户端手动测试一下相同文本。第三方api可以做很多限制和调整，我觉得这个问题是服务端造成的，应该找上游。
> 
> 不是，和你说的这个没什么关系，因为我这个也是在线模型，完全兼容GPT API，并不是本地模型啊。 而且我在插件的GPT配置里面点了“测试”，就一句话“hello world"也不行，也不是token超过限制。 同期用相同的密钥和API已经测试过可以使用GPT4 对话聊天。

那个本地模型也是完全兼容GPT API的，所以相同的错误反馈是有参考价值的。不过无所谓了，你先把你的自定义模型内容贴出来看看吧。我估计你用的应该是基于[这个模板](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/34#issuecomment-1538194936)。

**Comment by riverai** [comment]
> > > 参考[这里](https://github.com/nomic-ai/gpt4all/issues/1202#issue-1804862178)，可能是单次token量超载或者触发限制了吧，你可以在能聊天的客户端手动测试一下相同文本。第三方api可以做很多限制和调整，我觉得这个问题是服务端造成的，应该找上游。
> > 
> > 
> > 不是，和你说的这个没什么关系，因为我这个也是在线模型，完全兼容GPT API，并不是本地模型啊。 而且我在插件的GPT配置里面点了“测试”，就一句话“hello world"也不行，也不是token超过限制。 同期用相同的密钥和API已经测试过可以使用GPT4 对话聊天。
> 
> 那个本地模型也是完全兼容GPT API的，所以相同的错误反馈是有参考价值的。不过无所谓了，你先把你的自定义模型内容贴出来看看吧。我估计你用的应该是基于[这个模板](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/34#issuecomment-1538194936)。

其实还并不是。开头我是直接把GPT OpenAI的地址密钥都换成这个自定义的，就总是报错。
看了你这个模板，我就重新自建了一模板，然后换成了其他引擎，报错消失了。

不过这个模板模板默认没调节温度的地方

**Comment by anartigone** [comment]
> > > > 参考[这里](https://github.com/nomic-ai/gpt4all/issues/1202#issue-1804862178)，可能是单次token量超载或者触发限制了吧，你可以在能聊天的客户端手动测试一下相同文本。第三方api可以做很多限制和调整，我觉得这个问题是服务端造成的，应该找上游。
> > > 
> > > 
> > > 不是，和你说的这个没什么关系，因为我这个也是在线模型，完全兼容GPT API，并不是本地模型啊。 而且我在插件的GPT配置里面点了“测试”，就一句话“hello world"也不行，也不是token超过限制。 同期用相同的密钥和API已经测试过可以使用GPT4 对话聊天。
> > 
> > 
> > 那个本地模型也是完全兼容GPT API的，所以相同的错误反馈是有参考价值的。不过无所谓了，你先把你的自定义模型内容贴出来看看吧。我估计你用的应该是基于[这个模板](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/34#issuecomment-1538194936)。
> 
> 其实还并不是。开头我是直接把GPT OpenAI的地址密钥都换成这个自定义的，就总是报错。 看了你这个模板，我就重新自建了一模板，然后换成了其他引擎（从3.5换成3.5 16K)，报错消失了。
> 
> 不过这个模板模板默认没调节温度的地方

我觉得这个issue应该解决了，剩下的你自己研究官方[api文档](https://platform.openai.com/docs/api-reference/completions/create)吧，按语法塞进自定义模型模板里就行。
