### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by LIVEINTHEOC** [bookfere/Ebook-Translator-Calibre-Plugin#9]
反应几个问题
1.翻译完成后，原本设置保存文件的位置并没有找到已翻译的文件，会丢失。比如保存位置为桌面，实际桌面只有一个0字节的同名文件。
2.希望翻译完成之后，能够翻译内容单独输出，删除原文件内容，而不是用英文中文夹杂在一起。
以上两点。谢谢。

**Comment by bookfere** [comment]
旧版本插件会删除转换后的临时文件，新的版本去掉了这个步骤，把清理临时文件的工作交给了 Calibre，按理说应该不会再出现这个问题了，你可以再测试一下。第二个问题已经在新版本添加了选项，可以设置为不保留原文。
