### ISSUE TITLE
一本书的翻译任务会自动停止

### ISSUE THREAD

**Issue by riverai** [bookfere/Ebook-Translator-Calibre-Plugin#92]
一本书拆分2200字母到了490份。
我走之前是设置了除开前面3个不要翻译其他全部翻译的。
回来的时候，发现电脑上停止在了第220个任务附近，日志显示翻译完成，用时400分钟。

莫名其妙就自动停止了。

然后我继续选择220-490，选择翻译所选任务。
刚才发现，又自动停止在了360附近，还是显示翻译完成，用时...分钟。

然后我继续上面的操作，又停止在了390附近。

我看日志，翻译的译文都是确实停止在了这个编号，并不是已经完整跑了490个任务。
不过，每次停止的时候都是发生在报错的时候，似乎是报错或者其他什么操作，会让翻译任务提前终止，而不是先跳过报错的。查看报错的id编号，可以发现id编号和停止位置很接近，也就否定了是后面的所有内容都报错的可能性。

![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/3251548/d0df1eba-6170-4a14-9125-1fe8843efa43)
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/3251548/34b1c2b2-93b9-4ed4-838d-a645fd0c17d2)

**Comment by anartigone** [comment]
502比较少见，用的是什么翻译引擎？如果是自定义引擎请贴出参数。网络环境复杂吗？有用代理服务器或隧道工具吗？

**Comment by riverai** [comment]
> 502比较少见，用的是什么翻译引擎？如果是自定义引擎请贴出参数。网络环境复杂吗？有用代理服务器或隧道工具吗？

GPT40613，温度0.5.
然后用了代理。
我估计主要是因为网络不可能那么稳定，但是不稳定可以先跳过，结果报错了就容易所有任务都停下来。

**Comment by bookfere** [comment]
为满足 #76、#77 这两个需求，自 v2.1.0 开始在设置中添加了一个“**最大错误次数**”的选项，作用是当某个请求错误连续出现指定次数就停止翻译，预设是 **10** 次，如果不想自动停止则需要将其设为 **0**。

**Comment by riverai** [comment]
既然这个选项的作用和我之前猜测的一样，那么能否改变下这个选项的名字，比如改成”最大错误次数以终止翻译“，这样会直接表明功能，不要再有任何猜测。

书伴 ***@***.***> 于2023年7月19日周三 12:53写道：

**Comment by bookfere** [comment]
最初考虑过类似的描述（如“超过错误次数后停止翻译”、”取消翻译的错误次数阈值“），但是感觉在界面上显示太长就没采用，这就导致了语意模糊。还有就是这个选项是否适合放在“HTTP 请求”这一组设置中也有待商榷，因为它产生的后果是取消整个翻译任务，好像和请求本身没太大关联。

**Comment by bookfere** [comment]
不是，错误次数只在单个任务中共享。准确的说，在一个任务中，这 10 次错误次数必须是**连续**出现的，只要期间出现一个成功请求，错误次数就会被重新计数。

**Comment by bookfere** [comment]
暂时先把选项描述修改如下，如果有更好的方式再优化。

```
Error count to stop translation
超过错误次数停止翻译
```

**Comment by riverai** [comment]
> 暂时先把选项描述修改如下，如果有更好的方式再优化。
> 
> ```
> Error count to stop translation
> 超过错误次数停止翻译
> ```

既然都这么长了，何不加入 连续 呢。

另外除开上句话之外，我没问题了

**Comment by anartigone** [comment]
> 暂时先把选项描述修改如下，如果有更好的方式再优化。
> 
> ```
> Error count to stop translation
> 超过错误次数停止翻译
> ```

个人建议
UI显示：
```
Error Threshold
错误阈值
```
注释 (文档/浮动) ：
```
terminate translation when error count exceeds
超过错误次数中止翻译
```
