### ISSUE TITLE
生成翻译文件时，把markdown原文件的符号给带上吧？要不格式都变了

### ISSUE THREAD

**Issue by byq1** [bookfere/Ebook-Translator-Calibre-Plugin#97]

**Comment by bookfere** [comment]
同 [#37 (comment)](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/37#issuecomment-1542666918)。由于 Calibre 在处理 MarkDown 时无法保持原有的格式，因此插件也受此限制。
